/*
 WinChan is Copyright (c) 2012 Lloyd Hilaiel
 https://github.com/lloyd/winchan */
'use strict';var WinChan=function(){function c(a,d,b){a.attachEvent?a.attachEvent("on"+d,b):a.addEventListener&&a.addEventListener(d,b,!1)}function e(a,d,b){a.detachEvent?a.detachEvent("on"+d,b):a.removeEventListener&&a.removeEventListener(d,b,!1)}function b(a){/^https?:\/\//.test(a)||(a=window.location.href);var d=/^(https?:\/\/[\-_a-zA-Z\.0-9:]+)/.exec(a);return d?d[1]:a}var g="die",d,f=-1;"Microsoft Internet Explorer"===navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&
(f=parseFloat(RegExp.$1));d=8<=f;return window.JSON&&window.JSON.stringify&&window.JSON.parse&&window.postMessage?{open:function(a,f){function j(){l&&document.body.removeChild(l);l=void 0;if(r)try{r.close()}catch(a){m.postMessage(g,t)}r=m=void 0}function h(a){try{var d=JSON.parse(a.data);"ready"===d.a?m.postMessage(u,t):"error"===d.a?f&&(f(d.d),f=null):"response"===d.a&&(e(window,"message",h),e(window,"unload",j),j(),f&&(f(null,d.d),f=null))}catch(b){}}if(!f)throw"missing required callback argument";
var k;a.url||(k="missing required 'url' parameter");a.relay_url||(k="missing required 'relay_url' parameter");k&&setTimeout(function(){f(k)},0);a.window_name||(a.window_name=null);var p;if(!(p=!a.window_features))a:{try{var q=navigator.userAgent;p=-1!=q.indexOf("Fennec/")||-1!=q.indexOf("Firefox/")&&-1!=q.indexOf("Android");break a}catch(s){}p=!1}p&&(a.window_features=void 0);var l,t=b(a.url);if(t!==b(a.relay_url))return setTimeout(function(){f("invalid arguments: origin of url and relay_url must match")},
0);var m;d&&(l=document.createElement("iframe"),l.setAttribute("src",a.relay_url),l.style.display="none",l.setAttribute("name","__winchan_relay_frame"),document.body.appendChild(l),m=l.contentWindow);var r=window.open(a.url,a.window_name,a.window_features);m||(m=r);var u=JSON.stringify({a:"request",d:a.params});c(window,"unload",j);c(window,"message",h);return{close:j,focus:function(){if(r)try{r.focus()}catch(a){}}}},onOpen:function(a){function b(a){a=JSON.stringify(a);d?m.doPost(a,k):m.postMessage(a,
k)}function f(d){var c;try{c=JSON.parse(d.data)}catch(h){}c&&"request"===c.a&&(e(window,"message",f),k=d.origin,a&&setTimeout(function(){a(k,c.d,function(d){a=void 0;b({a:"response",d:d})})},0))}function h(a){if(a.data===g)try{window.close()}catch(d){}}var k="*",p;if(d)a:{for(var q=window.location,s=window.opener.frames,q=q.protocol+"//"+q.host,l=s.length-1;0<=l;l--)try{if(0===s[l].location.href.indexOf(q)&&"__winchan_relay_frame"===s[l].name){p=s[l];break a}}catch(t){}p=void 0}else p=window.opener;
var m=p;if(!m)throw"can't find relay frame";c(d?m:window,"message",f);c(d?m:window,"message",h);try{b({a:"ready"})}catch(r){c(m,"load",function(){b({a:"ready"})})}var u=function(){try{e(d?m:window,"message",h)}catch(f){}a&&b({a:"error",d:"client closed window"});a=void 0;try{window.close()}catch(c){}};c(window,"unload",u);return{detach:function(){e(window,"unload",u)}}}}:{open:function(a,d,b,f){setTimeout(function(){f("unsupported browser")},0)},onOpen:function(a){setTimeout(function(){a("unsupported browser")},
0)}}}();/*
 Copyright (c) 2013 David Benjamin and Alan Huang
 Use of this source code is governed by an MIT-style license that
 can be found at
 https://github.com/davidben/webathena
*/
var Err=function(c,e,b){this.ctx=c;this.code=e;this.msg=b};Err.Context={};Err.Context.KEY=2;Err.Context.NET=3;Err.Context.UNK=15;
var Crypto={randomNonce:function(){var c=sjcl.random.randomWords(1)[0];0>c&&(c+=2147483648);return c},retryForEntropy:function(c){var e=Q.defer(),b=function(){sjcl.random.removeEventListener("seeded",b);try{e.resolve(c())}catch(g){g instanceof sjcl.exception.notReady?sjcl.random.addEventListener("seeded",b):e.reject(g)}};b();return e.promise}},KDC=function(){function c(d){for(var b=0;b<d.length;b++)if(d[b].padataType==krb.PA_ETYPE_INFO2)return d=krb.ETYPE_INFO2.decodeDER(d[b].padataValue),void 0!==
d.salt&&(d.salt=arrayutils.fromUTF16(d.salt)),d;for(b=0;b<d.length;b++)if(d[b].padataType==krb.PA_ETYPE_INFO)return krb.ETYPE_INFO.decodeDER(d[b].padataValue);for(b=0;b<d.length;b++)if(d[b].padataType==krb.PA_PW_SALT)return[{salt:d[b].padataValue}];return[]}function e(b,f,a){f="salt"in b?b.salt:arrayutils.fromUTF16(f.realm+f.principalName.nameString.join(""));return krb.Key.fromPassword(b.etype,a,f,b.s2kparams)}var b={urlBase:"/kdc/v1/",Error:function(b,f){this.code=b;this.message=f}};b.Error.prototype.toString=
function(){return"KDC Error "+this.code+": "+this.message};b.NetworkError=function(b){this.message=b};b.NetworkError.prototype.toString=function(){return this.message};b.xhrRequest=function(d,f){var a=Q.defer(),c=new XMLHttpRequest;c.open("POST",b.urlBase+f);c.onreadystatechange=function(){4==this.readyState&&(200==this.status?a.resolve(this.responseText):this.status?a.reject(new b.NetworkError("HTTP error "+this.status+": "+this.statusText)):a.reject(new b.NetworkError("Network error")))};c.setRequestHeader("X-WebKDC-Request",
"OK");d?(c.setRequestHeader("Content-Type","text/plain"),c.send(arrayutils.toBase64(d))):c.send();return a.promise};b.kdcProxyRequest=function(d,c,a){return b.xhrRequest(d,c).then(function(d){d=JSON.parse(d);switch(d.status){case "ERROR":throw new b.NetworkError(d.msg);case "TIMEOUT":throw new b.NetworkError("KDC connection timed out");case "OK":return d=arrayutils.fromBase64(d.reply),a.decodeDER(d)[1]}})};b.asReq=function(d,c){return Crypto.retryForEntropy(function(){var a={};a.pvno=krb.pvno;a.msgType=
krb.KRB_MT_AS_REQ;void 0!==c&&(a.padata=c);a.reqBody={};a.reqBody.kdcOptions=krb.KDCOptions.make(krb.KDCOptions.forwardable,krb.KDCOptions.proxiable,krb.KDCOptions.renewable_ok);if(d.realm!=krb.realm)throw"Cross-realm not supported!";a.reqBody.principalName=d.principalName;a.reqBody.realm=krb.realm;a.reqBody.sname={};a.reqBody.sname.nameType=krb.KRB_NT_SRV_INST;a.reqBody.sname.nameString=["krbtgt",krb.realm];a.reqBody.till=new Date(0);a.reqBody.nonce=Crypto.randomNonce();a.reqBody.etype=krb.supportedEnctypes;
return b.kdcProxyRequest(krb.AS_REQ.encodeDER(a),"AS_REQ",krb.AS_REP_OR_ERROR).then(function(b){return{asReq:a,asRep:b}})})};var g={};g[krb.PA_ENC_TIMESTAMP]=function(b,f,a,g,j,h){b=c(a);f=null;for(a=0;a<b.length;a++)if(b[a].etype in kcrypto.encProfiles){f=b[a];break}if(null===f)throw new Err(Err.Context.KEY,3,"No supported enctypes");var k=e(f,j,h);return Crypto.retryForEntropy(function(){var a={};a.patimestamp=new Date;a.pausec=1E3*a.patimestamp.getUTCMilliseconds();a.patimestamp.setUTCMilliseconds(0);
a=k.encryptAs(krb.ENC_TS_ENC,krb.KU_AS_REQ_PA_ENC_TIMESTAMP,a);return{padataType:krb.PA_ENC_TIMESTAMP,padataValue:krb.ENC_TIMESTAMP.encodeDER(a)}})};b.getTGTSession=function(d,f){return b.asReq(d).then(function(a){var c=a.asReq,e=a.asRep;if(e.msgType==krb.KRB_MT_ERROR&&e.errorCode==krb.KDC_ERR_PREAUTH_REQUIRED)for(var h=krb.METHOD_DATA.decodeDER(e.eData),k=0;k<h.length;k++)if(h[k].padataType in g)return g[h[k].padataType](c,e,h,h[k],d,f).then(function(a){return b.asReq(d,[a])});return a}).then(function(a){var g=
a.asReq;a=a.asRep;if(a.msgType==krb.KRB_MT_ERROR)throw new b.Error(a.errorCode,a.eText);var j={};if(a.padata){var h=c(a.padata);if(h){if(1!=h.length)throw"Bad pre-auth hint";j=h[0];if("etype"in j&&j.etype!=a.encPart.etype)throw"Bad pre-auth hint";}}j.etype=a.encPart.etype;j=e(j,d,f);return b.sessionFromKDCRep(j,krb.KU_AS_REQ_ENC_PART,g,a)})};b.sessionFromKDCRep=function(b,c,a,e){if(a.reqBody.principalName){if(e.crealm!=a.reqBody.realm)throw new Err(Err.Context.KEY,16,"crealm does not match");if(!krb.principalNamesEqual(a.reqBody.principalName,
e.cname))throw new Err(Err.Context.KEY,17,"cname does not match");}b=b.decryptAs(krb.EncASorTGSRepPart,c,e.encPart)[1];if(a.reqBody.nonce!=b.nonce)throw new Err(Err.Context.KEY,18,"nonce does not match");if(!krb.principalNamesEqual(a.reqBody.sname,b.sname))throw new Err(Err.Context.KEY,19,"sname does not match");return new krb.Session(e,b)};b.getServiceSession=function(d,c){return Crypto.retryForEntropy(function(){var a={};a.pvno=krb.pvno;a.msgType=krb.KRB_MT_TGS_REQ;a.reqBody={};a.reqBody.kdcOptions=
krb.KDCOptions.make();a.reqBody.sname=c.principalName;a.reqBody.realm=c.realm;a.reqBody.till=new Date(0);a.reqBody.nonce=Crypto.randomNonce();a.reqBody.etype=krb.supportedEnctypes;var e=d.key.checksum(krb.KU_TGS_REQ_PA_TGS_REQ_CKSUM,krb.KDC_REQ_BODY.encodeDER(a.reqBody)),e=d.makeAPReq(krb.KU_TGS_REQ_PA_TGS_REQ,e).apReq;a.padata=[{padataType:krb.PA_TGS_REQ,padataValue:krb.AP_REQ.encodeDER(e)}];return b.kdcProxyRequest(krb.TGS_REQ.encodeDER(a),"TGS_REQ",krb.TGS_REP_OR_ERROR).then(function(c){if(c.msgType==
krb.KRB_MT_ERROR)throw new b.Error(c.errorCode,c.eText);return b.sessionFromKDCRep(d.key,krb.KU_TGS_REQ_ENC_PART,a,c)})})};return b}();function registerTicketAPI(){WinChan.onOpen(function(c,e,b){function g(){b({status:"DENIED",code:"NOT_ALLOWED"})}if(!e.realm||!e.principal)b({status:"ERROR",code:"BAD_REQUEST"});else if("https://"!=c.substring(0,8)&&"http://localhost:"!=c.substring(0,17))g();else{var d=new krb.Principal({nameType:krb.KRB_NT_UNKNOWN,nameString:e.principal},e.realm);getTGTSession().then(function(e){var a=e[0];e=e[1];var n=$("#request-ticket-template").children().clone();n.appendTo(document.body);e&&n.fadeIn();n.find(".client-principal").text(a.client.toString());
n.find(".foreign-origin").text(c);n.find(".service-principal").text(d.toString());n.find(".request-ticket-deny").click(g);n.find(".request-ticket-allow").click(function(){localStorage.getItem("tgtSession")?a.isExpired()?(log("Ticket expired"),g()):KDC.getServiceSession(a,d).then(function(a){b({status:"OK",session:a.toDict()})},function(a){log(a);g()}).done():(log("No ticket"),g())})}).done()}})};sjcl.random.startCollectors();KDC.xhrRequest(null,"urandom").then(function(c){c=arrayutils.fromBase64(c);c=new Uint32Array(c.buffer,c.byteOffset,c.byteLength/4);for(var e=[],b=0;b<c.length;b++)e.push(c[b]);sjcl.random.addEntropy(e,32*e.length,"server")}).done();
function showLoginPrompt(){var c=Q.defer(),e=$("#login-template").children().clone();e.appendTo(document.body);e.find(".username").focus();e.submit(function(b){b.preventDefault();$("#alert").slideUp(100);var g=$(this).find(".username")[0];b=$(this).find(".password")[0];var d=g.value,g=b.value,f=!1;d?$(this).find(".username + .error").fadeOut():($(this).find(".username + .error").fadeIn(),f=!0);g?$(this).find(".password + .error").fadeOut():($(this).find(".password + .error").fadeIn(),f=!0);if(!f){b.value=
"";var a=$(this).find(".submit"),n=a.text();a.attr("disabled","disabled").text(".");var j=setInterval(function(){a.text((a.text()+".").replace(".....","."))},500),h=function(){clearInterval(j);a.attr("disabled",null).text(n)};b=krb.Principal.fromString(d);KDC.getTGTSession(b,g).then(function(a){h();e.fadeOut(function(){$(this).remove()});c.resolve(a)},function(a){a=a instanceof kcrypto.DecryptionError?"Incorrect password!":a instanceof KDC.Error?a.code==krb.KDC_ERR_C_PRINCIPAL_UNKNOWN?"User does not exist!":
a.code==krb.KDC_ERR_PREAUTH_FAILED||a.code==krb.KRB_AP_ERR_BAD_INTEGRITY?"Incorrect password!":a.message:String(a);$("#alert-title").text("Error logging in:");$("#alert-text").text(a);$("#alert").slideDown(100);h()}).done()}});return c.promise}
function showRenewPrompt(c){var e=Q.defer(),b=$("#renew-template").children().clone();b.find(".client-principal").text(c.client.toString());b.find(".logout-link").click(function(c){c.preventDefault();b.remove();e.resolve(showLoginPrompt())});b.appendTo(document.body);b.find(".password").focus();b.submit(function(g){g.preventDefault();$("#alert").slideUp(100);g=$(this).find(".password")[0];var d=g.value;if(d){$(this).find(".password + .error").fadeOut();g.value="";var f=$(this).find(".submit"),a=f.text();
f.attr("disabled","disabled").text(".");var n=setInterval(function(){f.text((f.text()+".").replace(".....","."))},500),j=function(){clearInterval(n);f.attr("disabled",null).text(a)};KDC.getTGTSession(c.client,d).then(function(a){j();b.fadeOut(function(){$(this).remove()});e.resolve(a)},function(a){a=a instanceof kcrypto.DecryptionError?"Incorrect password!":a instanceof KDC.Error?a.code==krb.KDC_ERR_C_PRINCIPAL_UNKNOWN?"User does not exist!":a.code==krb.KDC_ERR_PREAUTH_FAILED||a.code==krb.KRB_AP_ERR_BAD_INTEGRITY?
"Incorrect password!":a.message:a instanceof KDC.NetworkError?a.message:String(a);$("#alert-title").text("Error logging in:");$("#alert-text").text(a);$("#alert").slideDown(100);j()}).done()}else $(this).find(".password + .error").fadeIn()});return e.promise}
function getTGTSession(){var c=localStorage.getItem("tgtSession");return c?(c=krb.Session.fromDict(JSON.parse(c)),c.isExpired()?showRenewPrompt(c).then(function(c){localStorage.setItem("tgtSession",JSON.stringify(c.toDict()));return[c,!0]}):Q.resolve([c,!1])):showLoginPrompt().then(function(c){localStorage.setItem("tgtSession",JSON.stringify(c.toDict()));return[c,!0]})}
$(function(){function c(){getTGTSession().then(function(e){var b=e[0];e=e[1];log(b);var g=$("#authed-template").children().clone();g.appendTo(document.body);e&&g.fadeIn();g.find(".client-principal").text(b.client.toString());g.find("button.logout").click(function(){localStorage.removeItem("tgtSession");g.remove();c()})}).done()}$('<img src="eye-small.png">').css({left:78,top:12}).appendTo("#logo");$('<img src="eye-large.png">').css({left:87,top:16}).appendTo("#logo");$('<img src="eye-large.png">').css({left:105,
top:16}).appendTo("#logo");$('<img src="eye-small.png">').css({left:121,top:12}).appendTo("#logo");$(document).mousemove(function(c){$("#logo img").each(function(){var b=c.pageX-$(this).offset().left-$(this).width()/2,g=c.pageY-$(this).offset().top-$(this).height()/2,b="rotate("+Math.atan2(b,-g)+"rad)";$(this).css({transform:b,"-moz-transform":b,"-webkit-transform":b,"-ms-transform":b,"-o-transform":b})})});$("#whatis a").click(function(){$("#info").slideToggle(0).css("height",$("#info").height()).slideToggle(0).slideToggle();
return!1});"#!request_ticket_v1"==location.hash?registerTicketAPI():c()});
//@ sourceMappingURL=webathena-ui.js.map
