/*
 WinChan is Copyright (c) 2012 Lloyd Hilaiel
 https://github.com/lloyd/winchan */
'use strict';var WinChan=function(){function e(b,a,c){b.attachEvent?b.attachEvent("on"+a,c):b.addEventListener&&b.addEventListener(a,c,!1)}function d(b,a,c){b.detachEvent?b.detachEvent("on"+a,c):b.removeEventListener&&b.removeEventListener(a,c,!1)}function a(){try{var b=navigator.userAgent;return-1!=b.indexOf("Fennec/")||-1!=b.indexOf("Firefox/")&&-1!=b.indexOf("Android")}catch(a){}return!1}function f(b){/^https?:\/\//.test(b)||(b=window.location.href);var a=/^(https?:\/\/[\-_a-zA-Z\.0-9:]+)/.exec(b);
return a?a[1]:b}function c(){for(var b=window.location,a=window.opener.frames,b=b.protocol+"//"+b.host,c=a.length-1;0<=c;c--)try{if(0===a[c].location.href.indexOf(b)&&a[c].name===h)return a[c]}catch(e){}}var h="__winchan_relay_frame",b="die",n=function(){var b=-1;"Microsoft Internet Explorer"===navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(b=parseFloat(RegExp.$1));return 8<=b}();return window.JSON&&window.JSON.stringify&&window.JSON.parse&&window.postMessage?{open:function(c,
g){function m(){l&&document.body.removeChild(l);l=void 0;t&&(t=clearInterval(t));d(window,"message",u);d(window,"unload",m);if(r)try{r.close()}catch(c){p.postMessage(b,s)}r=p=void 0}function u(b){if(b.origin===s)try{var c=JSON.parse(b.data);"ready"===c.a?p.postMessage(v,s):"error"===c.a?(m(),g&&(g(c.d),g=null)):"response"===c.a&&(m(),g&&(g(null,c.d),g=null))}catch(a){}}if(!g)throw"missing required callback argument";var q;c.url||(q="missing required 'url' parameter");c.relay_url||(q="missing required 'relay_url' parameter");
q&&setTimeout(function(){g(q)},0);c.window_name||(c.window_name=null);if(!c.window_features||a())c.window_features=void 0;var l,s=f(c.url);if(s!==f(c.relay_url))return setTimeout(function(){g("invalid arguments: origin of url and relay_url must match")},0);var p;n&&(l=document.createElement("iframe"),l.setAttribute("src",c.relay_url),l.style.display="none",l.setAttribute("name",h),document.body.appendChild(l),p=l.contentWindow);var r=window.open(c.url,c.window_name,c.window_features);p||(p=r);var t=
setInterval(function(){r&&r.closed&&(m(),g&&(g("unknown closed window"),g=null))},500),v=JSON.stringify({a:"request",d:c.params});e(window,"unload",m);e(window,"message",u);return{close:m,focus:function(){if(r)try{r.focus()}catch(b){}}}},onOpen:function(a){function h(b){b=JSON.stringify(b);n?l.doPost(b,q):l.postMessage(b,q)}function m(b){var c;try{c=JSON.parse(b.data)}catch(e){}c&&"request"===c.a&&(d(window,"message",m),q=b.origin,a&&setTimeout(function(){a(q,c.d,function(b){a=void 0;h({a:"response",
d:b})})},0))}function f(c){if(c.data===b)try{window.close()}catch(a){}}var q="*",l=n?c():window.opener;if(!l)throw"can't find relay frame";e(n?l:window,"message",m);e(n?l:window,"message",f);try{h({a:"ready"})}catch(s){e(l,"load",function(b){h({a:"ready"})})}var p=function(){try{d(n?l:window,"message",f)}catch(b){}a&&h({a:"error",d:"client closed window"});a=void 0;try{window.close()}catch(c){}};e(window,"unload",p);return{detach:function(){d(window,"unload",p)}}}}:{open:function(b,c,a,h){setTimeout(function(){h("unsupported browser")},
0)},onOpen:function(b){setTimeout(function(){b("unsupported browser")},0)}}}();/*
 Copyright (c) 2013 David Benjamin and Alan Huang
 Use of this source code is governed by an MIT-style license that
 can be found at
 https://github.com/davidben/webathena
*/
var Err=function(e,d,a){this.ctx=e;this.code=d;this.msg=a};Err.Context={};Err.Context.KEY=2;Err.Context.NET=3;Err.Context.UNK=15;
var Crypto={randomNonce:function(){var e=sjcl.random.randomWords(1)[0];0>e&&(e+=2147483648);return e},retryForEntropy:function(e){var d=Q.defer(),a=function(){sjcl.random.removeEventListener("seeded",a);try{d.resolve(e())}catch(f){f instanceof sjcl.exception.notReady?sjcl.random.addEventListener("seeded",a):d.reject(f)}};a();return d.promise}},KDC=function(){function e(c){for(var a=0;a<c.length;a++)if(c[a].padataType==krb.PA_ETYPE_INFO2)return c=krb.ETYPE_INFO2.decodeDER(c[a].padataValue),void 0!==
c.salt&&(c.salt=arrayutils.fromString(c.salt)),c;for(a=0;a<c.length;a++)if(c[a].padataType==krb.PA_ETYPE_INFO)return krb.ETYPE_INFO.decodeDER(c[a].padataValue);for(a=0;a<c.length;a++)if(c[a].padataType==krb.PA_PW_SALT)return[{salt:c[a].padataValue}];return[]}function d(c,a,b){a="salt"in c?c.salt:arrayutils.fromString(a.realm+a.principalName.nameString.join(""));return krb.Key.fromPassword(c.etype,b,a,c.s2kparams)}var a={urlBase:"/kdc/v1/",Error:function(a,e){this.code=a;this.message=e}};a.Error.prototype.toString=
function(){return"KDC Error "+this.code+": "+this.message};a.NetworkError=function(a){this.message=a};a.NetworkError.prototype.toString=function(){return this.message};a.xhrRequest=function(c,e){var b=Q.defer(),d=new XMLHttpRequest;d.open("POST",a.urlBase+e);d.onreadystatechange=function(c){4==this.readyState&&(200==this.status?b.resolve(this.responseText):this.status?b.reject(new a.NetworkError("HTTP error "+this.status+": "+this.statusText)):b.reject(new a.NetworkError("Network error")))};d.setRequestHeader("X-WebKDC-Request",
"OK");c?(d.setRequestHeader("Content-Type","text/plain"),d.send(arrayutils.toBase64(c))):d.send();return b.promise};a.kdcProxyRequest=function(c,d,b){return a.xhrRequest(c,d).then(function(c){c=JSON.parse(c);switch(c.status){case "ERROR":throw new a.NetworkError(c.msg);case "TIMEOUT":throw new a.NetworkError("KDC connection timed out");case "OK":return c=arrayutils.fromBase64(c.reply),b.decodeDER(c)[1]}})};a.asReq=function(c,d){return Crypto.retryForEntropy(function(){var b={};b.pvno=krb.pvno;b.msgType=
krb.KRB_MT_AS_REQ;void 0!==d&&(b.padata=d);b.reqBody={};b.reqBody.kdcOptions=krb.KDCOptions.make(krb.KDCOptions.forwardable,krb.KDCOptions.proxiable,krb.KDCOptions.renewable_ok);if(c.realm!=krb.realm)throw"Cross-realm not supported!";b.reqBody.principalName=c.principalName;b.reqBody.realm=krb.realm;b.reqBody.sname={};b.reqBody.sname.nameType=krb.KRB_NT_SRV_INST;b.reqBody.sname.nameString=["krbtgt",krb.realm];b.reqBody.till=new Date(0);b.reqBody.nonce=Crypto.randomNonce();b.reqBody.etype=krb.supportedEnctypes;
return a.kdcProxyRequest(krb.AS_REQ.encodeDER(b),"AS_REQ",krb.AS_REP_OR_ERROR).then(function(a){return{asReq:b,asRep:a}})})};var f={};f[krb.PA_ENC_TIMESTAMP]=function(a,f,b,n,k,g){a=e(b);f=null;for(b=0;b<a.length;b++)if(a[b].etype in kcrypto.encProfiles){f=a[b];break}if(null===f)throw new Err(Err.Context.KEY,3,"No supported enctypes");var m=d(f,k,g);return Crypto.retryForEntropy(function(){var a={};a.patimestamp=new Date;a.pausec=1E3*a.patimestamp.getUTCMilliseconds();a.patimestamp.setUTCMilliseconds(0);
a=m.encryptAs(krb.ENC_TS_ENC,krb.KU_AS_REQ_PA_ENC_TIMESTAMP,a);return{padataType:krb.PA_ENC_TIMESTAMP,padataValue:krb.ENC_TIMESTAMP.encodeDER(a)}})};a.getTGTSession=function(c,h){return a.asReq(c).then(function(b){var d=b.asReq,e=b.asRep;if(e.msgType==krb.KRB_MT_ERROR&&e.errorCode==krb.KDC_ERR_PREAUTH_REQUIRED)for(var g=krb.METHOD_DATA.decodeDER(e.eData),m=0;m<g.length;m++)if(g[m].padataType in f)return f[g[m].padataType](d,e,g,g[m],c,h).then(function(b){return a.asReq(c,[b])});return b}).then(function(b){var f=
b.asReq;b=b.asRep;if(b.msgType==krb.KRB_MT_ERROR)throw new a.Error(b.errorCode,b.eText);var k={};if(b.padata){var g=e(b.padata);if(g){if(1!=g.length)throw"Bad pre-auth hint";k=g[0];if("etype"in k&&k.etype!=b.encPart.etype)throw"Bad pre-auth hint";}}k.etype=b.encPart.etype;k=d(k,c,h);return a.sessionFromKDCRep(k,krb.KU_AS_REQ_ENC_PART,f,b)})};a.sessionFromKDCRep=function(a,d,b,e){if(b.reqBody.principalName){if(e.crealm!=b.reqBody.realm)throw new Err(Err.Context.KEY,16,"crealm does not match");if(!krb.principalNamesEqual(b.reqBody.principalName,
e.cname))throw new Err(Err.Context.KEY,17,"cname does not match");}a=a.decryptAs(krb.EncASorTGSRepPart,d,e.encPart)[1];if(b.reqBody.nonce!=a.nonce)throw new Err(Err.Context.KEY,18,"nonce does not match");if(!krb.principalNamesEqual(b.reqBody.sname,a.sname))throw new Err(Err.Context.KEY,19,"sname does not match");return new krb.Session(e,a)};a.getServiceSession=function(c,e){return Crypto.retryForEntropy(function(){var b={};b.pvno=krb.pvno;b.msgType=krb.KRB_MT_TGS_REQ;b.reqBody={};b.reqBody.kdcOptions=
krb.KDCOptions.make(krb.KDCOptions.forwardable);b.reqBody.sname=e.principalName;b.reqBody.realm=e.realm;b.reqBody.till=new Date(0);b.reqBody.nonce=Crypto.randomNonce();b.reqBody.etype=krb.supportedEnctypes;var d=c.key.checksum(krb.KU_TGS_REQ_PA_TGS_REQ_CKSUM,krb.KDC_REQ_BODY.encodeDER(b.reqBody)),d=c.makeAPReq(krb.KU_TGS_REQ_PA_TGS_REQ,d).apReq;b.padata=[{padataType:krb.PA_TGS_REQ,padataValue:krb.AP_REQ.encodeDER(d)}];return a.kdcProxyRequest(krb.TGS_REQ.encodeDER(b),"TGS_REQ",krb.TGS_REP_OR_ERROR).then(function(d){if(d.msgType==
krb.KRB_MT_ERROR)throw new a.Error(d.errorCode,d.eText);return a.sessionFromKDCRep(c.key,krb.KU_TGS_REQ_ENC_PART,b,d)})})};return a}();var SERVICES={};SERVICES["krbtgt/"+krb.realm+"@"+krb.realm]={dangerous:!0,desc:"Full access to your Athena account"};SERVICES["moira/moira7.mit.edu@"+krb.realm]={dangerous:!0,desc:"View and modify your mailing lists and groups"};SERVICES["afs/athena.mit.edu@"+krb.realm]={dangerous:!0,desc:"Full access to all your files on Athena"};SERVICES["zephyr/zephyr@"+krb.realm]={desc:"Send and receive zephyr notices as you"};
function makeServiceNode(e){var d=e.toString(),a=document.createElement("li"),f=document.createElement("abbr");a.appendChild(f);f.title=d;if(d in SERVICES)e=SERVICES[d],e.dangerous&&(a.className="dangerous"),$(f).text(e.desc);else{var c=document.createElement("code"),h=null;c.className="identifier";2===e.principalName.nameString.length&&"host"===e.principalName.nameString[0]?$(c).text(e.principalName.nameString[1]):2===e.principalName.nameString.length&&"HTTP"===e.principalName.nameString[0]?(h=document.createTextNode("web services on "),
$(c).text(e.principalName.nameString[1])):$(c).text(d);f.appendChild(document.createTextNode("Access "));h&&f.appendChild(h);f.appendChild(c);f.appendChild(document.createTextNode(" on your behalf"))}return a}
function registerTicketAPI(){WinChan.onOpen(function(e,d,a){function f(a,b){if("string"!==typeof b)throw new TypeError;if(!(a instanceof Array))throw new TypeError;a.forEach(function(a){if("string"!==typeof a)throw new TypeError;});return new krb.Principal({nameType:krb.KRB_NT_UNKNOWN,nameString:a},b)}function c(){a({status:"DENIED",code:"NOT_ALLOWED"})}var h=[],b=!0;try{if(d.services){if(!(d.services instanceof Array))throw TypeError();h=d.services.map(function(a){return f(a.principal,a.realm)});
if(0==h.length)throw Error();}else h=[f(d.principal,d.realm)],b=!1}catch(n){throw a({status:"ERROR",code:"BAD_REQUEST"}),n;}var k=null;if(d.user)try{k=f(d.user.principal,d.user.realm)}catch(g){throw a({status:"ERROR",code:"BAD_REQUEST"}),g;}"https://"!=e.substring(0,8)&&"http://localhost:"!=e.substring(0,17)?c():getTGTSession().then(function(d){var f=d[0];d=d[1];if(!k||f.client.realm==k.realm&&krb.principalNamesEqual(f.client.principalName,k.principalName)){var g=$("#request-ticket-template").children().clone();
g.appendTo(document.body);d&&g.fadeIn();g.find(".client-principal").text(f.client.toString());g.find(".foreign-origin").text(e);var l=g.find(".permission-list");h.forEach(function(a){l.append(makeServiceNode(a))});g.find(".service-principal").text(h.map(function(a){return a.toString()}).join(", "));g.find(".request-ticket-deny").click(c);g.find(".request-ticket-allow").click(function(d){localStorage.getItem("tgtSession")?f.isExpired()?(log("Ticket expired"),c()):Q.all(h.map(function(a){return KDC.getServiceSession(f,
a)})).then(function(c){b?a({status:"OK",sessions:c.map(function(a){return a.toDict()})}):a({status:"OK",session:c[0].toDict()})},function(a){log(a);c()}).done():(log("No ticket"),c())})}else a({status:"DENIED",code:"WRONG_USER"})}).done()})};sjcl.random.startCollectors();KDC.xhrRequest(null,"urandom").then(function(e){e=arrayutils.fromBase64(e);e=new Uint32Array(e.buffer,e.byteOffset,e.byteLength/4);for(var d=[],a=0;a<e.length;a++)d.push(e[a]);sjcl.random.addEntropy(d,32*d.length,"server")}).done();
function showLoginPrompt(){var e=Q.defer(),d=$("#login-template").children().clone();d.appendTo(document.body);d.find(".username").focus();d.find("form").submit(function(a){a.preventDefault();$("#alert").slideUp(100);var f=$(this).find(".username")[0];a=$(this).find(".password")[0];var c=f.value,f=a.value,h=!1;c?$(this).find(".username + .error").fadeOut():($(this).find(".username + .error").fadeIn(),h=!0);f?$(this).find(".password + .error").fadeOut():($(this).find(".password + .error").fadeIn(),
h=!0);if(!h){a.value="";var b=$(this).find(".submit"),n=b.text();b.attr("disabled","disabled").text(".");var k=setInterval(function(){b.text((b.text()+".").replace(".....","."))},500),g=function(){clearInterval(k);b.attr("disabled",null).text(n)};a=krb.Principal.fromString(c);KDC.getTGTSession(a,f).then(function(a){g();var b=d.get(0).getBoundingClientRect(),c=d.offsetParent().get(0).getBoundingClientRect();d.css({margin:"0",position:"absolute",top:b.top-c.top+"px",left:b.left-c.left+"px"});d.fadeOut(function(){$(this).remove()});
e.resolve(a)},function(a){a=a instanceof kcrypto.DecryptionError?"Incorrect password!":a instanceof KDC.Error?a.code==krb.KDC_ERR_C_PRINCIPAL_UNKNOWN?"User does not exist!":a.code==krb.KDC_ERR_PREAUTH_FAILED||a.code==krb.KRB_AP_ERR_BAD_INTEGRITY?"Incorrect password!":a.message:String(a);$("#alert-title").text("Error logging in:");$("#alert-text").text(a);$("#alert").slideDown(100);g()}).done()}});return e.promise}
function showRenewPrompt(e){var d=Q.defer(),a=$("#renew-template").children().clone();a.find(".client-principal").text(e.client.toString());a.find(".logout-link").click(function(e){e.preventDefault();a.remove();d.resolve(showLoginPrompt())});a.appendTo(document.body);a.find(".password").focus();a.find("form").submit(function(f){f.preventDefault();$("#alert").slideUp(100);f=$(this).find(".password")[0];var c=f.value;if(c){$(this).find(".password + .error").fadeOut();f.value="";var h=$(this).find(".submit"),
b=h.text();h.attr("disabled","disabled").text(".");var n=setInterval(function(){h.text((h.text()+".").replace(".....","."))},500),k=function(){clearInterval(n);h.attr("disabled",null).text(b)};KDC.getTGTSession(e.client,c).then(function(b){k();var c=a.get(0).getBoundingClientRect(),e=a.offsetParent().get(0).getBoundingClientRect();a.css({margin:"0",position:"absolute",top:c.top-e.top+"px",left:c.left-e.left+"px"});a.fadeOut(function(){$(this).remove()});d.resolve(b)},function(a){a=a instanceof kcrypto.DecryptionError?
"Incorrect password!":a instanceof KDC.Error?a.code==krb.KDC_ERR_C_PRINCIPAL_UNKNOWN?"User does not exist!":a.code==krb.KDC_ERR_PREAUTH_FAILED||a.code==krb.KRB_AP_ERR_BAD_INTEGRITY?"Incorrect password!":a.message:a instanceof KDC.NetworkError?a.message:String(a);$("#alert-title").text("Error logging in:");$("#alert-text").text(a);$("#alert").slideDown(100);k()}).done()}else $(this).find(".password + .error").fadeIn()});return d.promise}
function getTGTSession(){"1"!==localStorage.getItem("version")&&(localStorage.clear(),localStorage.setItem("version","1"));var e=localStorage.getItem("tgtSession");return e?(e=krb.Session.fromDict(JSON.parse(e)),36E5>e.timeRemaining()?showRenewPrompt(e).then(function(d){localStorage.setItem("tgtSession",JSON.stringify(d.toDict()));return[d,!0]}):Q.resolve([e,!1])):showLoginPrompt().then(function(d){localStorage.setItem("tgtSession",JSON.stringify(d.toDict()));return[d,!0]})}
$(function(){function e(){getTGTSession().then(function(d){var a=d[0];d=d[1];log(a);var f=$("#authed-template").children().clone();f.appendTo(document.body);d&&f.fadeIn();f.find(".client-principal").text(a.client.toString());f.find("button.logout").click(function(){localStorage.removeItem("tgtSession");f.remove();e()})}).done()}$('<img src="eye-small.png">').css({left:78,top:12}).appendTo("#logo");$('<img src="eye-large.png">').css({left:87,top:16}).appendTo("#logo");$('<img src="eye-large.png">').css({left:105,
top:16}).appendTo("#logo");$('<img src="eye-small.png">').css({left:121,top:12}).appendTo("#logo");$(document).mousemove(function(d){$("#logo img").each(function(){var a=d.pageX-$(this).offset().left-$(this).width()/2,e=d.pageY-$(this).offset().top-$(this).height()/2,a="rotate("+Math.atan2(a,-e)+"rad)";$(this).css({transform:a})})});$("#whatis a").click(function(){$("#info").slideToggle(0).css("height",$("#info").height()).slideToggle(0).slideToggle();return!1});"#!request_ticket_v1"==location.hash?
registerTicketAPI():e()});
//@ sourceMappingURL=webathena-ui.js.map
