/*
CryptoJS v3.x
code.google.com/p/crypto-js
(c) 2009-2012 by Jeff Mott. All rights reserved.
code.google.com/p/crypto-js/wiki/License
*/
var CryptoJS=CryptoJS||function(g,i){var c={},f=c.lib={},j=f.Base=function(){function a(){}return{extend:function(t){a.prototype=this;var b=new a;t&&b.mixIn(t);b.$super=this;return b},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.$super.extend(this)}}}(),h=f.WordArray=j.extend({init:function(a,b){a=
this.words=a||[];this.sigBytes=b!=i?b:4*a.length},toString:function(a){return(a||k).stringify(this)},concat:function(a){var b=this.words,r=a.words,d=this.sigBytes,a=a.sigBytes;this.clamp();if(d%4)for(var c=0;c<a;c++)b[d+c>>>2]|=(r[c>>>2]>>>24-8*(c%4)&255)<<24-8*((d+c)%4);else if(65535<r.length)for(c=0;c<a;c+=4)b[d+c>>>2]=r[c>>>2];else b.push.apply(b,r);this.sigBytes+=a;return this},clamp:function(){var a=this.words,b=this.sigBytes;a[b>>>2]&=4294967295<<32-8*(b%4);a.length=g.ceil(b/4)},clone:function(){var a=
j.clone.call(this);a.words=this.words.slice(0);return a},random:function(a){return h.create(window.getRandomBytes(a),a)}}),n=c.enc={},k=n.Hex={stringify:function(a){for(var b=a.words,a=a.sigBytes,c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-8*(d%4)&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d+=2)c[d>>>3]|=parseInt(a.substr(d,2),16)<<24-4*(d%8);return h.create(c,b/2)}},q=n.Latin1={stringify:function(a){for(var b=a.words,
a=a.sigBytes,c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>2]>>>24-8*(d%4)&255));return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d++)c[d>>>2]|=(a.charCodeAt(d)&255)<<24-8*(d%4);return h.create(c,b)}},m=n.Utf8={stringify:function(a){try{return decodeURIComponent(escape(q.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(a){return q.parse(unescape(encodeURIComponent(a)))}},b=f.BufferedBlockAlgorithm=j.extend({reset:function(){this._data=h.create();
this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=m.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var b=this._data,c=b.words,d=b.sigBytes,e=this.blockSize,f=d/(4*e),f=a?g.ceil(f):g.max((f|0)-this._minBufferSize,0),a=f*e,d=g.min(4*a,d);if(a){for(var m=0;m<a;m+=e)this._doProcessBlock(c,m);m=c.splice(0,a);b.sigBytes-=d}return h.create(m,d)},clone:function(){var a=j.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});f.Hasher=b.extend({init:function(){this.reset()},
reset:function(){b.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);this._doFinalize();return this._hash},clone:function(){var a=b.clone.call(this);a._hash=this._hash.clone();return a},blockSize:16,_createHelper:function(a){return function(b,c){return a.create(c).finalize(b)}},_createHmacHelper:function(a){return function(b,c){return e.HMAC.create(a,c).finalize(b)}}});var e=c.algo={};return c}(Math);
(function(g){var i=CryptoJS,c=i.lib,f=c.WordArray,c=c.Hasher,j=i.algo,h=[],n=[];(function(){function c(a){for(var b=g.sqrt(a),e=2;e<=b;e++)if(!(a%e))return!1;return!0}function f(a){return 4294967296*(a-(a|0))|0}for(var b=2,e=0;64>e;)c(b)&&(8>e&&(h[e]=f(g.pow(b,0.5))),n[e]=f(g.pow(b,1/3)),e++),b++})();var k=[],j=j.SHA256=c.extend({_doReset:function(){this._hash=f.create(h.slice(0))},_doProcessBlock:function(c,f){for(var b=this._hash.words,e=b[0],a=b[1],g=b[2],j=b[3],d=b[4],h=b[5],i=b[6],s=b[7],l=0;64>
l;l++){if(16>l)k[l]=c[f+l]|0;else{var o=k[l-15],p=k[l-2];k[l]=((o<<25|o>>>7)^(o<<14|o>>>18)^o>>>3)+k[l-7]+((p<<15|p>>>17)^(p<<13|p>>>19)^p>>>10)+k[l-16]}o=s+((d<<26|d>>>6)^(d<<21|d>>>11)^(d<<7|d>>>25))+(d&h^~d&i)+n[l]+k[l];p=((e<<30|e>>>2)^(e<<19|e>>>13)^(e<<10|e>>>22))+(e&a^e&g^a&g);s=i;i=h;h=d;d=j+o|0;j=g;g=a;a=e;e=o+p|0}b[0]=b[0]+e|0;b[1]=b[1]+a|0;b[2]=b[2]+g|0;b[3]=b[3]+j|0;b[4]=b[4]+d|0;b[5]=b[5]+h|0;b[6]=b[6]+i|0;b[7]=b[7]+s|0},_doFinalize:function(){var c=this._data,f=c.words,b=8*this._nDataBytes,
e=8*c.sigBytes;f[e>>>5]|=128<<24-e%32;f[(e+64>>>9<<4)+15]=b;c.sigBytes=4*f.length;this._process()}});i.SHA256=c._createHelper(j);i.HmacSHA256=c._createHmacHelper(j)})(Math);
(function(){var g=CryptoJS,i=g.enc.Utf8;g.algo.HMAC=g.lib.Base.extend({init:function(c,f){c=this._hasher=c.create();"string"==typeof f&&(f=i.parse(f));var g=c.blockSize,h=4*g;f.sigBytes>h&&(f=c.finalize(f));for(var n=this._oKey=f.clone(),k=this._iKey=f.clone(),q=n.words,m=k.words,b=0;b<g;b++)q[b]^=1549556828,m[b]^=909522486;n.sigBytes=k.sigBytes=h;this.reset()},reset:function(){var c=this._hasher;c.reset();c.update(this._iKey)},update:function(c){this._hasher.update(c);return this},finalize:function(c){var f=
this._hasher,c=f.finalize(c);f.reset();return f.finalize(this._oKey.clone().concat(c))}})})();
