"use strict";var q=void 0,r=!1;var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},invalid:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},bug:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},notReady:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}}};
"undefined"!=typeof module&&module.exports&&(module.exports=sjcl);
sjcl.cipher.aes=function(a){this.j[0][0][0]||this.A();var b,c,e,d,f=this.j[0][4],g=this.j[1];b=a.length;var h=1;if(4!==b&&6!==b&&8!==b)throw new sjcl.exception.invalid("invalid aes key size");this.a=[e=a.slice(0),d=[]];for(a=b;a<4*b+28;a++){c=e[a-1];if(0===a%b||8===b&&4===a%b)c=f[c>>>24]<<24^f[c>>16&255]<<16^f[c>>8&255]<<8^f[c&255],0===a%b&&(c=c<<8^c>>>24^h<<24,h=h<<1^283*(h>>7));e[a]=e[a-b]^c}for(b=0;a;b++,a--)c=e[b&3?a:a-4],d[b]=4>=a||4>b?c:g[0][f[c>>>24]]^g[1][f[c>>16&255]]^g[2][f[c>>8&255]]^g[3][f[c&
255]]};
sjcl.cipher.aes.prototype={encrypt:function(a){return x(this,a,0)},decrypt:function(a){return x(this,a,1)},j:[[[],[],[],[],[]],[[],[],[],[],[]]],A:function(){var a=this.j[0],b=this.j[1],c=a[4],e=b[4],d,f,g,h=[],k=[],n,m,l,p;for(d=0;0x100>d;d++)k[(h[d]=d<<1^283*(d>>7))^d]=d;for(f=g=0;!c[f];f^=n||1,g=k[g]||1){l=g^g<<1^g<<2^g<<3^g<<4;l=l>>8^l&255^99;c[f]=l;e[l]=f;m=h[d=h[n=h[f]]];p=0x1010101*m^0x10001*d^0x101*n^0x1010100*f;m=0x101*h[l]^0x1010100*l;for(d=0;4>d;d++)a[d][f]=m=m<<24^m>>>8,b[d][l]=p=p<<24^p>>>8}for(d=
0;5>d;d++)a[d]=a[d].slice(0),b[d]=b[d].slice(0)}};
function x(a,b,c){if(4!==b.length)throw new sjcl.exception.invalid("invalid aes block size");var e=a.a[c],d=b[0]^e[0],f=b[c?3:1]^e[1],g=b[2]^e[2];b=b[c?1:3]^e[3];var h,k,n,m=e.length/4-2,l,p=4,s=[0,0,0,0];h=a.j[c];a=h[0];var t=h[1],u=h[2],v=h[3],w=h[4];for(l=0;l<m;l++)h=a[d>>>24]^t[f>>16&255]^u[g>>8&255]^v[b&255]^e[p],k=a[f>>>24]^t[g>>16&255]^u[b>>8&255]^v[d&255]^e[p+1],n=a[g>>>24]^t[b>>16&255]^u[d>>8&255]^v[f&255]^e[p+2],b=a[b>>>24]^t[d>>16&255]^u[f>>8&255]^v[g&255]^e[p+3],p+=4,d=h,f=k,g=n;for(l=
0;4>l;l++)s[c?3&-l:l]=w[d>>>24]<<24^w[f>>16&255]<<16^w[g>>8&255]<<8^w[b&255]^e[p++],h=d,d=f,f=g,g=b,b=h;return s}
sjcl.bitArray={bitSlice:function(a,b,c){a=sjcl.bitArray.J(a.slice(b/32),32-(b&31)).slice(1);return c===q?a:sjcl.bitArray.clamp(a,c-b)},extract:function(a,b,c){var e=Math.floor(-b-c&31);return((b+c-1^b)&-32?a[b/32|0]<<32-e^a[b/32+1|0]>>>e:a[b/32|0]>>>e)&(1<<c)-1},concat:function(a,b){if(0===a.length||0===b.length)return a.concat(b);var c=a[a.length-1],e=sjcl.bitArray.getPartial(c);return 32===e?a.concat(b):sjcl.bitArray.J(b,e,c|0,a.slice(0,a.length-1))},bitLength:function(a){var b=a.length;return 0===
b?0:32*(b-1)+sjcl.bitArray.getPartial(a[b-1])},clamp:function(a,b){if(32*a.length<b)return a;a=a.slice(0,Math.ceil(b/32));var c=a.length;b&=31;0<c&&b&&(a[c-1]=sjcl.bitArray.partial(b,a[c-1]&2147483648>>b-1,1));return a},partial:function(a,b,c){return 32===a?b:(c?b|0:b<<32-a)+0x10000000000*a},getPartial:function(a){return Math.round(a/0x10000000000)||32},equal:function(a,b){if(sjcl.bitArray.bitLength(a)!==sjcl.bitArray.bitLength(b))return r;var c=0,e;for(e=0;e<a.length;e++)c|=a[e]^b[e];return 0===
c},J:function(a,b,c,e){var d;d=0;for(e===q&&(e=[]);32<=b;b-=32)e.push(c),c=0;if(0===b)return e.concat(a);for(d=0;d<a.length;d++)e.push(c|a[d]>>>b),c=a[d]<<32-b;d=a.length?a[a.length-1]:0;a=sjcl.bitArray.getPartial(d);e.push(sjcl.bitArray.partial(b+a&31,32<b+a?c:e.pop(),1));return e},Q:function(a,b){return[a[0]^b[0],a[1]^b[1],a[2]^b[2],a[3]^b[3]]}};
sjcl.codec.utf8String={fromBits:function(a){var b="",c=sjcl.bitArray.bitLength(a),e,d;for(e=0;e<c/8;e++)0===(e&3)&&(d=a[e/4]),b+=String.fromCharCode(d>>>24),d<<=8;return decodeURIComponent(escape(b))},toBits:function(a){a=unescape(encodeURIComponent(a));var b=[],c,e=0;for(c=0;c<a.length;c++)e=e<<8|a.charCodeAt(c),3===(c&3)&&(b.push(e),e=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),e));return b}};
sjcl.codec.base64={F:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",fromBits:function(a,b,c){var e="",d=0,f=sjcl.codec.base64.F,g=0,h=sjcl.bitArray.bitLength(a);c&&(f=f.substr(0,62)+"-_");for(c=0;6*e.length<h;)e+=f.charAt((g^a[c]>>>d)>>>26),6>d?(g=a[c]<<6-d,d+=26,c++):(g<<=6,d-=6);for(;e.length&3&&!b;)e+="=";return e},toBits:function(a,b){a=a.replace(/\s|=/g,"");var c=[],e,d=0,f=sjcl.codec.base64.F,g=0,h;b&&(f=f.substr(0,62)+"-_");for(e=0;e<a.length;e++){h=f.indexOf(a.charAt(e));
if(0>h)throw new sjcl.exception.invalid("this isn't base64!");26<d?(d-=26,c.push(g^h>>>d),g=h<<32-d):(d+=6,g^=h<<32-d)}d&56&&c.push(sjcl.bitArray.partial(d&56,g,1));return c}};sjcl.codec.base64url={fromBits:function(a){return sjcl.codec.base64.fromBits(a,1,1)},toBits:function(a){return sjcl.codec.base64.toBits(a,1)}};sjcl.hash.sha256=function(a){this.a[0]||this.A();a?(this.d=a.d.slice(0),this.c=a.c.slice(0),this.b=a.b):this.reset()};sjcl.hash.sha256.hash=function(a){return(new sjcl.hash.sha256).update(a).finalize()};
sjcl.hash.sha256.prototype={blockSize:512,reset:function(){this.d=this.o.slice(0);this.c=[];this.b=0;return this},update:function(a){"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this.c=sjcl.bitArray.concat(this.c,a);b=this.b;a=this.b=b+sjcl.bitArray.bitLength(a);for(b=512+b&-512;b<=a;b+=512)this.m(c.splice(0,16));return this},finalize:function(){var a,b=this.c,c=this.d,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this.b/
4294967296));for(b.push(this.b|0);b.length;)this.m(b.splice(0,16));this.reset();return c},o:[],a:[],A:function(){function a(a){return 0x100000000*(a-Math.floor(a))|0}var b=0,c=2,e;a:for(;64>b;c++){for(e=2;e*e<=c;e++)if(0===c%e)continue a;8>b&&(this.o[b]=a(Math.pow(c,0.5)));this.a[b]=a(Math.pow(c,1/3));b++}},m:function(a){var b,c,e=a.slice(0),d=this.d,f=this.a,g=d[0],h=d[1],k=d[2],n=d[3],m=d[4],l=d[5],p=d[6],s=d[7];for(a=0;64>a;a++)16>a?b=e[a]:(b=e[a+1&15],c=e[a+14&15],b=e[a&15]=(b>>>7^b>>>18^b>>>3^
b<<25^b<<14)+(c>>>17^c>>>19^c>>>10^c<<15^c<<13)+e[a&15]+e[a+9&15]|0),b=b+s+(m>>>6^m>>>11^m>>>25^m<<26^m<<21^m<<7)+(p^m&(l^p))+f[a],s=p,p=l,l=m,m=n+b|0,n=k,k=h,h=g,g=b+(h&k^n&(h^k))+(h>>>2^h>>>13^h>>>22^h<<30^h<<19^h<<10)|0;d[0]=d[0]+g|0;d[1]=d[1]+h|0;d[2]=d[2]+k|0;d[3]=d[3]+n|0;d[4]=d[4]+m|0;d[5]=d[5]+l|0;d[6]=d[6]+p|0;d[7]=d[7]+s|0}};sjcl.hash.sha1=function(a){a?(this.d=a.d.slice(0),this.c=a.c.slice(0),this.b=a.b):this.reset()};sjcl.hash.sha1.hash=function(a){return(new sjcl.hash.sha1).update(a).finalize()};
sjcl.hash.sha1.prototype={blockSize:512,reset:function(){this.d=this.o.slice(0);this.c=[];this.b=0;return this},update:function(a){"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this.c=sjcl.bitArray.concat(this.c,a);b=this.b;a=this.b=b+sjcl.bitArray.bitLength(a);for(b=this.blockSize+b&-this.blockSize;b<=a;b+=this.blockSize)this.m(c.splice(0,16));return this},finalize:function(){var a,b=this.c,c=this.d,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);
b.push(Math.floor(this.b/0x100000000));for(b.push(this.b|0);b.length;)this.m(b.splice(0,16));this.reset();return c},o:[1732584193,4023233417,2562383102,271733878,3285377520],a:[1518500249,1859775393,2400959708,3395469782],m:function(a){var b,c,e,d,f,g,h=a.slice(0),k=this.d;c=k[0];e=k[1];d=k[2];f=k[3];g=k[4];for(a=0;79>=a;a++)16<=a&&(h[a]=(h[a-3]^h[a-8]^h[a-14]^h[a-16])<<1|(h[a-3]^h[a-8]^h[a-14]^h[a-16])>>>31),b=19>=a?e&d|~e&f:39>=a?e^d^f:59>=a?e&d|e&f|d&f:79>=a?e^d^f:q,b=(c<<5|c>>>27)+b+g+h[a]+this.a[Math.floor(a/
20)]|0,g=f,f=d,d=e<<30|e>>>2,e=c,c=b;k[0]=k[0]+c|0;k[1]=k[1]+e|0;k[2]=k[2]+d|0;k[3]=k[3]+f|0;k[4]=k[4]+g|0}};sjcl.misc.hmac=function(a,b){this.H=b=b||sjcl.hash.sha256;var c=[[],[]],e,d=b.prototype.blockSize/32;this.l=[new b,new b];a.length>d&&(a=b.hash(a));for(e=0;e<d;e++)c[0][e]=a[e]^909522486,c[1][e]=a[e]^1549556828;this.l[0].update(c[0]);this.l[1].update(c[1]);this.C=new b(this.l[0])};
sjcl.misc.hmac.prototype.encrypt=sjcl.misc.hmac.prototype.mac=function(a){if(this.K)throw new sjcl.exception.invalid("encrypt on already updated hmac called!");this.update(a);return this.digest(a)};sjcl.misc.hmac.prototype.reset=function(){this.C=new this.H(this.l[0]);this.K=r};sjcl.misc.hmac.prototype.update=function(a){this.K=!0;this.C.update(a)};sjcl.misc.hmac.prototype.digest=function(){var a=this.C.finalize(),a=(new this.H(this.l[1])).update(a).finalize();this.reset();return a};
sjcl.misc.pbkdf2=function(a,b,c,e,d){c=c||1E3;if(0>e||0>c)throw sjcl.exception.invalid("invalid params to pbkdf2");"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));d=d||sjcl.misc.hmac;a=new d(a);var f,g,h,k,n=[],m=sjcl.bitArray;for(k=1;32*n.length<(e||1);k++){d=f=a.encrypt(m.concat(b,[k]));for(g=1;g<c;g++){f=a.encrypt(f);for(h=0;h<f.length;h++)d[h]^=f[h]}n=n.concat(d)}e&&(n=m.clamp(n,e));return n};
sjcl.prng=function(a){this.e=[new sjcl.hash.sha256];this.h=[0];this.B=0;this.r={};this.z=0;this.G={};this.I=this.f=this.i=this.P=0;this.a=[0,0,0,0,0,0,0,0];this.g=[0,0,0,0];this.v=q;this.w=a;this.n=r;this.u={progress:{},seeded:{}};this.k=this.O=0;this.s=1;this.t=2;this.M=0x10000;this.D=[0,48,64,96,128,192,0x100,384,512,768,1024];this.N=3E4;this.L=80};
sjcl.prng.prototype={randomWords:function(a,b){var c=[],e;e=this.isReady(b);var d;if(e===this.k)throw new sjcl.exception.notReady("generator isn't seeded");if(e&this.t){e=!(e&this.s);d=[];var f=0,g;this.I=d[0]=(new Date).valueOf()+this.N;for(g=0;16>g;g++)d.push(0x100000000*Math.random()|0);for(g=0;g<this.e.length&&!(d=d.concat(this.e[g].finalize()),f+=this.h[g],this.h[g]=0,!e&&this.B&1<<g);g++);this.B>=1<<this.e.length&&(this.e.push(new sjcl.hash.sha256),this.h.push(0));this.f-=f;f>this.i&&(this.i=
f);this.B++;this.a=sjcl.hash.sha256.hash(this.a.concat(d));this.v=new sjcl.cipher.aes(this.a);for(e=0;4>e&&!(this.g[e]=this.g[e]+1|0,this.g[e]);e++);}for(e=0;e<a;e+=4)0===(e+1)%this.M&&y(this),d=z(this),c.push(d[0],d[1],d[2],d[3]);y(this);return c.slice(0,a)},setDefaultParanoia:function(a){this.w=a},addEntropy:function(a,b,c){c=c||"user";var e,d,f=(new Date).valueOf(),g=this.r[c],h=this.isReady(),k=0;e=this.G[c];e===q&&(e=this.G[c]=this.P++);g===q&&(g=this.r[c]=0);this.r[c]=(this.r[c]+1)%this.e.length;
switch(typeof a){case "number":b===q&&(b=1);this.e[g].update([e,this.z++,1,b,f,1,a|0]);break;case "object":c=Object.prototype.toString.call(a);if("[object Uint32Array]"===c){d=[];for(c=0;c<a.length;c++)d.push(a[c]);a=d}else{"[object Array]"!==c&&(k=1);for(c=0;c<a.length&&!k;c++)"number"!=typeof a[c]&&(k=1)}if(!k){if(b===q)for(c=b=0;c<a.length;c++)for(d=a[c];0<d;)b++,d>>>=1;this.e[g].update([e,this.z++,2,b,f,a.length].concat(a))}break;case "string":b===q&&(b=a.length);this.e[g].update([e,this.z++,
3,b,f,a.length]);this.e[g].update(a);break;default:k=1}if(k)throw new sjcl.exception.bug("random: addEntropy only supports number, array of numbers or string");this.h[g]+=b;this.f+=b;h===this.k&&(this.isReady()!==this.k&&A("seeded",Math.max(this.i,this.f)),A("progress",this.getProgress()))},isReady:function(a){a=this.D[a!==q?a:this.w];return this.i&&this.i>=a?this.h[0]>this.L&&(new Date).valueOf()>this.I?this.t|this.s:this.s:this.f>=a?this.t|this.k:this.k},getProgress:function(a){a=this.D[a?a:this.w];
return this.i>=a?1:this.f>a?1:this.f/a},startCollectors:function(){if(!this.n){if(window.addEventListener)window.addEventListener("load",this.p,r),window.addEventListener("mousemove",this.q,r);else if(document.attachEvent)document.attachEvent("onload",this.p),document.attachEvent("onmousemove",this.q);else throw new sjcl.exception.bug("can't attach event");this.n=!0}},stopCollectors:function(){this.n&&(window.removeEventListener?(window.removeEventListener("load",this.p,r),window.removeEventListener("mousemove",
this.q,r)):window.detachEvent&&(window.detachEvent("onload",this.p),window.detachEvent("onmousemove",this.q)),this.n=r)},addEventListener:function(a,b){this.u[a][this.O++]=b},removeEventListener:function(a,b){var c,e,d=this.u[a],f=[];for(e in d)d.hasOwnProperty(e)&&d[e]===b&&f.push(e);for(c=0;c<f.length;c++)e=f[c],delete d[e]},q:function(a){sjcl.random.addEntropy([a.x||a.clientX||a.offsetX||0,a.y||a.clientY||a.offsetY||0],2,"mouse")},p:function(){sjcl.random.addEntropy((new Date).valueOf(),2,"loadtime")}};
function A(a,b){var c,e=sjcl.random.u[a],d=[];for(c in e)e.hasOwnProperty(c)&&d.push(e[c]);for(c=0;c<d.length;c++)d[c](b)}function y(a){a.a=z(a).concat(z(a));a.v=new sjcl.cipher.aes(a.a)}function z(a){for(var b=0;4>b&&!(a.g[b]=a.g[b]+1|0,a.g[b]);b++);return a.v.encrypt(a.g)}sjcl.random=new sjcl.prng(6);
try{if("undefined"!==typeof module&&module.exports){var B=require("crypto").randomBytes(128);sjcl.random.addEntropy(B,1024,"crypto['randomBytes']")}else if(window){var C;window.crypto&&window.crypto.getRandomValues?C=window.crypto.getRandomValues:window.msCrypto&&window.msCrypto.getRandomValues&&(C=window.msCrypto.getRandomValues);if(C){var D=new Uint32Array(32);C(D);sjcl.random.addEntropy(D,1024,"crypto['getRandomValues']")}}}catch(E){};
