/*

=============================================================================== 
Crc32 is a JavaScript function for computing the CRC32 of a string 
............................................................................... 

Version: 1.2 - 2006/11 - http://noteslog.com/category/javascript/ 

------------------------------------------------------------------------------- 
Copyright (c) 2006 Andrea Ercolino 
http://www.opensource.org/licenses/mit-license.php 
=============================================================================== 
*/
'use strict';var crc32=function(){return function(a,c){c==window.undefined&&(c=0);var b=0,b=0;c^=-1;for(var d=0,e=a.length;d<e;d++)b=(c^a.charCodeAt(d))&255,b="0x"+"00000000 77073096 EE0E612C 990951BA 076DC419 706AF48F E963A535 9E6495A3 0EDB8832 79DCB8A4 E0D5E91E 97D2D988 09B64C2B 7EB17CBD E7B82D07 90BF1D91 1DB71064 6AB020F2 F3B97148 84BE41DE 1ADAD47D 6DDDE4EB F4D4B551 83D385C7 136C9856 646BA8C0 FD62F97A 8A65C9EC 14015C4F 63066CD9 FA0F3D63 8D080DF5 3B6E20C8 4C69105E D56041E4 A2677172 3C03E4D1 4B04D447 D20D85FD A50AB56B 35B5A8FA 42B2986C DBBBC9D6 ACBCF940 32D86CE3 45DF5C75 DCD60DCF ABD13D59 26D930AC 51DE003A C8D75180 BFD06116 21B4F4B5 56B3C423 CFBA9599 B8BDA50F 2802B89E 5F058808 C60CD9B2 B10BE924 2F6F7C87 58684C11 C1611DAB B6662D3D 76DC4190 01DB7106 98D220BC EFD5102A 71B18589 06B6B51F 9FBFE4A5 E8B8D433 7807C9A2 0F00F934 9609A88E E10E9818 7F6A0DBB 086D3D2D 91646C97 E6635C01 6B6B51F4 1C6C6162 856530D8 F262004E 6C0695ED 1B01A57B 8208F4C1 F50FC457 65B0D9C6 12B7E950 8BBEB8EA FCB9887C 62DD1DDF 15DA2D49 8CD37CF3 FBD44C65 4DB26158 3AB551CE A3BC0074 D4BB30E2 4ADFA541 3DD895D7 A4D1C46D D3D6F4FB 4369E96A 346ED9FC AD678846 DA60B8D0 44042D73 33031DE5 AA0A4C5F DD0D7CC9 5005713C 270241AA BE0B1010 C90C2086 5768B525 206F85B3 B966D409 CE61E49F 5EDEF90E 29D9C998 B0D09822 C7D7A8B4 59B33D17 2EB40D81 B7BD5C3B C0BA6CAD EDB88320 9ABFB3B6 03B6E20C 74B1D29A EAD54739 9DD277AF 04DB2615 73DC1683 E3630B12 94643B84 0D6D6A3E 7A6A5AA8 E40ECF0B 9309FF9D 0A00AE27 7D079EB1 F00F9344 8708A3D2 1E01F268 6906C2FE F762575D 806567CB 196C3671 6E6B06E7 FED41B76 89D32BE0 10DA7A5A 67DD4ACC F9B9DF6F 8EBEEFF9 17B7BE43 60B08ED5 D6D6A3E8 A1D1937E 38D8C2C4 4FDFF252 D1BB67F1 A6BC5767 3FB506DD 48B2364B D80D2BDA AF0A1B4C 36034AF6 41047A60 DF60EFC3 A867DF55 316E8EEF 4669BE79 CB61B38C BC66831A 256FD2A0 5268E236 CC0C7795 BB0B4703 220216B9 5505262F C5BA3BBE B2BD0B28 2BB45A92 5CB36A04 C2D7FFA7 B5D0CF31 2CD99E8B 5BDEAE1D 9B64C2B0 EC63F226 756AA39C 026D930A 9C0906A9 EB0E363F 72076785 05005713 95BF4A82 E2B87A14 7BB12BAE 0CB61B38 92D28E9B E5D5BE0D 7CDCEFB7 0BDBDF21 86D3D2D4 F1D4E242 68DDB3F8 1FDA836E 81BE16CD F6B9265B 6FB077E1 18B74777 88085AE6 FF0F6A70 66063BCA 11010B5C 8F659EFF F862AE69 616BFFD3 166CCF45 A00AE278 D70DD2EE 4E048354 3903B3C2 A7672661 D06016F7 4969474D 3E6E77DB AED16A4A D9D65ADC 40DF0B66 37D83BF0 A9BCAE53 DEBB9EC5 47B2CF7F 30B5FFE9 BDBDF21C CABAC28A 53B39330 24B4A3A6 BAD03605 CDD70693 54DE5729 23D967BF B3667A2E C4614AB8 5D681B02 2A6F2B94 B40BBE37 C30C8EA1 5A05DF1B 2D02EF8D".substr(9*
b,8),c=c>>>8^b;return c^-1}}();/*

 Copyright (c) 2010, Linden Research, Inc.
 Copyright (c) 2012, Joshua Bell

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 $/LicenseInfo$
*/
(function(a){function c(){try{return document&&document.createTextNode("").splitText(1),new RangeError("INDEX_SIZE_ERR")}catch(a){return a}}function b(a){if(Object.getOwnPropertyNames&&Object.defineProperty){var c=Object.getOwnPropertyNames(a),b;for(b=0;b<c.length;b+=1)Object.defineProperty(a,c[b],{value:a[c[b]],writable:!1,enumerable:!1,configurable:!1})}}function d(a){function c(b){Object.defineProperty(a,b,{get:function(){return a._getter(b)},set:function(c){a._setter(b,c)},enumerable:!0,configurable:!1})}
if(Object.defineProperty){var b;for(b=0;b<a.length;b+=1)c(b)}}function e(a,c){var b=32-c;return a<<b>>b}function g(a,c){var b=32-c;return a<<b>>>b}function p(a){return[a&255]}function v(a){return e(a[0],8)}function D(a){return[a&255]}function y(a){return g(a[0],8)}function B(a){a=Math.round(Number(a));return[0>a?0:255<a?255:a&255]}function E(a){return[a>>8&255,a&255]}function f(a){return e(a[0]<<8|a[1],16)}function w(a){return[a>>8&255,a&255]}function F(a){return g(a[0]<<8|a[1],16)}function z(a){return[a>>
24&255,a>>16&255,a>>8&255,a&255]}function A(a){return e(a[0]<<24|a[1]<<16|a[2]<<8|a[3],32)}function G(a){return[a>>24&255,a>>16&255,a>>8&255,a&255]}function x(a){return g(a[0]<<24|a[1]<<16|a[2]<<8|a[3],32)}function k(a,c,b){var d=(1<<c-1)-1,k,e,h;a!==a?(e=(1<<d)-1,d=Math.pow(2,b-1),k=0):Infinity===a||-Infinity===a?(e=(1<<d)-1,d=0,k=0>a?1:0):0===a?(d=e=0,k=-Infinity===1/a?1:0):(k=0>a,a=Math.abs(a),a>=Math.pow(2,1-d)?(h=Math.min(Math.floor(Math.log(a)/Math.LN2),d),e=h+d,d=Math.round(a*Math.pow(2,b-
h)-Math.pow(2,b))):(e=0,d=Math.round(a/Math.pow(2,1-d-b))));for(a=[];b;b-=1)a.push(d%2?1:0),d=Math.floor(d/2);for(b=c;b;b-=1)a.push(e%2?1:0),e=Math.floor(e/2);a.push(k?1:0);a.reverse();c=a.join("");for(k=[];c.length;)k.push(parseInt(c.substring(0,8),2)),c=c.substring(8);return k}function u(a,c,b){var d=[],k,e,h;for(k=a.length;k;k-=1)for(h=a[k-1],e=8;e;e-=1)d.push(h%2?1:0),h>>=1;d.reverse();e=d.join("");a=(1<<c-1)-1;d=parseInt(e.substring(0,1),2)?-1:1;k=parseInt(e.substring(1,1+c),2);e=parseInt(e.substring(1+
c),2);return k===(1<<c)-1?0!==e?NaN:Infinity*d:0<k?d*Math.pow(2,k-a)*(1+e/Math.pow(2,b)):0!==e?d*Math.pow(2,-(a-1))*(e/Math.pow(2,b)):0>d?-0:0}function h(a){return u(a,11,52)}function H(a){return k(a,11,52)}function I(a){return u(a,8,23)}function m(a){return k(a,8,23)}var l=function(){var a=Object.prototype.toString,c=Object.prototype.hasOwnProperty;return{Class:function(c){return a.call(c).replace(/^\[object *|\]$/g,"")},HasProperty:function(a,c){return c in a},HasOwnProperty:function(a,b){return c.call(a,
b)},IsCallable:function(a){return"function"===typeof a},ToInt32:function(a){return a>>0},ToUint32:function(a){return a>>>0}}}(),q;if(!(q=!Object.defineProperty)){var r;try{Object.defineProperty({},"x",{}),r=!0}catch(C){r=!1}q=!r}q&&(Object.defineProperty=function(a,c,b){if(!a===Object(a))throw new TypeError("Object.defineProperty called on non-object");l.HasProperty(b,"get")&&Object.prototype.__defineGetter__&&Object.prototype.__defineGetter__.call(a,c,b.get);l.HasProperty(b,"set")&&Object.prototype.__defineSetter__&&
Object.prototype.__defineSetter__.call(a,c,b.set);l.HasProperty(b,"value")&&(a[c]=b.value);return a});Object.getOwnPropertyNames||(Object.getOwnPropertyNames=function(a){if(a!==Object(a))throw new TypeError("Object.getOwnPropertyNames called on non-object");var c=[],b;for(b in a)l.HasOwnProperty(a,b)&&c.push(b);return c});(function(){function k(a,h,f){var m;m=function(a,k,h){var f,g,q;if(arguments.length&&"number"!==typeof arguments[0])if("object"===typeof arguments[0]&&arguments[0].constructor===
m)for(f=arguments[0],this.length=f.length,this.byteLength=this.length*this.BYTES_PER_ELEMENT,this.buffer=new e(this.byteLength),g=this.byteOffset=0;g<this.length;g+=1)this._setter(g,f._getter(g));else if("object"!==typeof arguments[0]||arguments[0]instanceof e||"ArrayBuffer"===l.Class(arguments[0]))if("object"===typeof arguments[0]&&(arguments[0]instanceof e||"ArrayBuffer"===l.Class(arguments[0]))){this.buffer=a;this.byteOffset=l.ToUint32(k);if(this.byteOffset>this.buffer.byteLength)throw c();if(this.byteOffset%
this.BYTES_PER_ELEMENT)throw new RangeError("ArrayBuffer length minus the byteOffset is not a multiple of the element size.");if(3>arguments.length){this.byteLength=this.buffer.byteLength-this.byteOffset;if(this.byteLength%this.BYTES_PER_ELEMENT)throw c();this.length=this.byteLength/this.BYTES_PER_ELEMENT}else this.length=l.ToUint32(h),this.byteLength=this.length*this.BYTES_PER_ELEMENT;if(this.byteOffset+this.byteLength>this.buffer.byteLength)throw c();}else throw new TypeError("Unexpected argument type(s)");
else for(f=arguments[0],this.length=l.ToUint32(f.length),this.byteLength=this.length*this.BYTES_PER_ELEMENT,this.buffer=new e(this.byteLength),g=this.byteOffset=0;g<this.length;g+=1)q=f[g],this._setter(g,Number(q));else{this.length=l.ToInt32(arguments[0]);if(0>h)throw new RangeError("ArrayBufferView size is not a small enough positive integer.");this.byteLength=this.length*this.BYTES_PER_ELEMENT;this.buffer=new e(this.byteLength);this.byteOffset=0}this.constructor=m;b(this);d(this)};m.prototype=new g;
m.prototype.BYTES_PER_ELEMENT=a;m.prototype._pack=h;m.prototype._unpack=f;m.BYTES_PER_ELEMENT=a;m.prototype._getter=function(a){if(1>arguments.length)throw new SyntaxError("Not enough arguments");a=l.ToUint32(a);if(!(a>=this.length)){var c=[],b,d;b=0;for(d=this.byteOffset+a*this.BYTES_PER_ELEMENT;b<this.BYTES_PER_ELEMENT;b+=1,d+=1)c.push(this.buffer._bytes[d]);return this._unpack(c)}};m.prototype.get=m.prototype._getter;m.prototype._setter=function(a,c){if(2>arguments.length)throw new SyntaxError("Not enough arguments");
a=l.ToUint32(a);if(!(a>=this.length)){var b=this._pack(c),d,k;d=0;for(k=this.byteOffset+a*this.BYTES_PER_ELEMENT;d<this.BYTES_PER_ELEMENT;d+=1,k+=1)this.buffer._bytes[k]=b[d]}};m.prototype.set=function(a,b){if(1>arguments.length)throw new SyntaxError("Not enough arguments");var d,k,e,h,f,m;if("object"===typeof arguments[0]&&arguments[0].constructor===this.constructor){d=arguments[0];k=l.ToUint32(arguments[1]);if(k+d.length>this.length)throw c();m=this.byteOffset+k*this.BYTES_PER_ELEMENT;k=d.length*
this.BYTES_PER_ELEMENT;if(d.buffer===this.buffer){e=[];h=0;for(f=d.byteOffset;h<k;h+=1,f+=1)e[h]=d.buffer._bytes[f];for(h=0;h<k;h+=1,m+=1)this.buffer._bytes[m]=e[h]}else for(h=0,f=d.byteOffset;h<k;h+=1,f+=1,m+=1)this.buffer._bytes[m]=d.buffer._bytes[f]}else if("object"===typeof arguments[0]&&"undefined"!==typeof arguments[0].length){d=arguments[0];e=l.ToUint32(d.length);k=l.ToUint32(arguments[1]);if(k+e>this.length)throw c();for(h=0;h<e;h+=1)f=d[h],this._setter(k+h,Number(f))}else throw new TypeError("Unexpected argument type(s)");
};m.prototype.subarray=function(a,c){a=l.ToInt32(a);c=l.ToInt32(c);1>arguments.length&&(a=0);2>arguments.length&&(c=this.length);0>a&&(a=this.length+a);0>c&&(c=this.length+c);a=0>a?0:a>this.length?this.length:a;c=0>c?0:c>this.length?this.length:c;var b=c-a;0>b&&(b=0);return new this.constructor(this.buffer,this.byteOffset+a*this.BYTES_PER_ELEMENT,b)};return m}var e=function(a){a=l.ToInt32(a);if(0>a)throw new RangeError("ArrayBuffer size is not a small enough positive integer.");this.byteLength=a;
this._bytes=[];this._bytes.length=a;for(a=0;a<this.byteLength;a+=1)this._bytes[a]=0;b(this)},g=function(){},q=k(1,p,v),u=k(1,D,y),r=k(1,B,y),C=k(2,E,f),J=k(2,w,F),K=k(4,z,A),L=k(4,G,x),M=k(4,m,I),N=k(8,H,h);a.ArrayBuffer=a.ArrayBuffer||e;a.Int8Array=a.Int8Array||q;a.Uint8Array=a.Uint8Array||u;a.Uint8ClampedArray=a.Uint8ClampedArray||r;a.Int16Array=a.Int16Array||C;a.Uint16Array=a.Uint16Array||J;a.Int32Array=a.Int32Array||K;a.Uint32Array=a.Uint32Array||L;a.Float32Array=a.Float32Array||M;a.Float64Array=
a.Float64Array||N})();(function(){function d(a,c){return l.IsCallable(a.get)?a.get(c):a[c]}function k(a){return function(b,k){b=l.ToUint32(b);if(b+a.BYTES_PER_ELEMENT>this.byteLength)throw c();b+=this.byteOffset;var e=new Uint8Array(this.buffer,b,a.BYTES_PER_ELEMENT),f=[],m;for(m=0;m<a.BYTES_PER_ELEMENT;m+=1)f.push(d(e,m));Boolean(k)===Boolean(h)&&f.reverse();return d(new a((new Uint8Array(f)).buffer),0)}}function e(a){return function(b,k,e){b=l.ToUint32(b);if(b+a.BYTES_PER_ELEMENT>this.byteLength)throw c();
k=new a([k]);k=new Uint8Array(k.buffer);var f=[],m;for(m=0;m<a.BYTES_PER_ELEMENT;m+=1)f.push(d(k,m));Boolean(e)===Boolean(h)&&f.reverse();(new Uint8Array(this.buffer,b,a.BYTES_PER_ELEMENT)).set(f)}}var h=function(){var a=new Uint16Array([4660]),a=new Uint8Array(a.buffer);return 18===d(a,0)}(),f=function(a,d,k){if(0===arguments.length)a=new ArrayBuffer(0);else if(!(a instanceof ArrayBuffer||"ArrayBuffer"===l.Class(a)))throw new TypeError("TypeError");this.buffer=a||new ArrayBuffer(0);this.byteOffset=
l.ToUint32(d);if(this.byteOffset>this.buffer.byteLength)throw c();this.byteLength=3>arguments.length?this.buffer.byteLength-this.byteOffset:l.ToUint32(k);if(this.byteOffset+this.byteLength>this.buffer.byteLength)throw c();b(this)};f.prototype.getUint8=k(Uint8Array);f.prototype.getInt8=k(Int8Array);f.prototype.getUint16=k(Uint16Array);f.prototype.getInt16=k(Int16Array);f.prototype.getUint32=k(Uint32Array);f.prototype.getInt32=k(Int32Array);f.prototype.getFloat32=k(Float32Array);f.prototype.getFloat64=
k(Float64Array);f.prototype.setUint8=e(Uint8Array);f.prototype.setInt8=e(Int8Array);f.prototype.setUint16=e(Uint16Array);f.prototype.setInt16=e(Int16Array);f.prototype.setUint32=e(Uint32Array);f.prototype.setInt32=e(Int32Array);f.prototype.setFloat32=e(Float32Array);f.prototype.setFloat64=e(Float64Array);a.DataView=a.DataView||f})()})(this);/*
 Copyright (c) 2013 David Benjamin and Alan Huang
 Use of this source code is governed by an MIT-style license that
 can be found at
 https://github.com/davidben/webathena
*/
function log(a){"undefined"!=typeof console&&console.log&&console.log(a)}
window.atob&&window.btoa||function(){var a={fromBits:function(a){var b="",d=sjcl.bitArray.bitLength(a),e,g;for(e=0;e<d/8;e++)0===(e&3)&&(g=a[e/4]),b+=String.fromCharCode(g>>>24),g<<=8;return b},toBits:function(a){var b=[],d,e=0;for(d=0;d<a.length;d++)e=e<<8|a.charCodeAt(d),3===(d&3)&&(b.push(e),e=0);d&3&&b.push(sjcl.bitArray.partial(8*(d&3),e));return b}};window.atob=function(c){return a.fromBits(sjcl.codec.base64.toBits(c))};window.btoa=function(c){return sjcl.codec.base64.fromBits(a.toBits(c))}}();
window.Uint8Array&&0!==(new Uint8Array(1)).subarray(1).byteLength&&function(){for(var a=function(a,b){a|=0;b|=0;1>arguments.length&&(a=0);2>arguments.length&&(b=this.length);0>a&&(a=this.length+a);0>b&&(b=this.length+b);a=0>a?0:a>this.length?this.length:a;b=0>b?0:b>this.length?this.length:b;var c=b-a;0>c&&(c=0);return new this.constructor(this.buffer,this.byteOffset+a*this.BYTES_PER_ELEMENT,c)},c="Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),
b=0;b<c.length;b++)window[c[b]]&&(window[c[b]].prototype.subarray=a)}();String.prototype.startsWith||Object.defineProperty(String.prototype,"startsWith",{enumerable:!1,configurable:!1,writable:!1,value:function(a,c){return this.substr(c||0,a.length)===a}});var arrayutils=function(){var a={asUint8Array:function(a){return a instanceof Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength)},fromByteString:function(a){for(var c=new Uint8Array(a.length),e=0;e<a.length;e++)c[e]=a.charCodeAt(e);return c}};if(Uint8Array.prototype._getter)a.toByteString=function(b){b=a.asUint8Array(b);for(var c="",e=0;e<b.length;e++)c+=String.fromCharCode(b._getter(e));return c};else try{String.fromCharCode.apply(String,new Uint8Array([1,2,3])),a.toByteString=function(c){return String.fromCharCode.apply(String,
a.asUint8Array(c))}}catch(c){a.toByteString=function(c){c=a.asUint8Array(c);for(var d="",e=0;e<c.length;e++)d+=String.fromCharCode(c[e]);return d}}a.fromString=function(c){return a.fromByteString(unescape(encodeURIComponent(c)))};a.toString=function(c){return decodeURIComponent(escape(a.toByteString(c)))};a.fromBase64=function(c){return a.fromByteString(atob(c))};a.toBase64=function(c){return btoa(a.toByteString(c))};a.fromSJCL=function(a){var c=sjcl.bitArray.bitLength(a),e,g,p=new Uint8Array(c>>>
3);for(e=0;e<c/8;e++)0===(e&3)&&(g=a[e/4]),p[e]=g>>>24,g<<=8;return p};a.toSJCL=function(c){c=a.asUint8Array(c);var d=[],e,g=0;for(e=0;e<c.length;e++)g=g<<8|c[e],3===(e&3)&&(d.push(g),g=0);e&3&&d.push(sjcl.bitArray.partial(8*(e&3),g));return d};a.fromCryptoJS=function(a){var c=a.words;a=a.sigBytes;for(var e=new Uint8Array(a),g=0;g<a;g++)e[g]=c[g>>>2]>>>24-8*(g%4)&255;return e};a.toCryptoJS=function(c){c=a.asUint8Array(c);for(var d=c.length,e=[],g=0;g<d;g++)e[g>>>2]|=c[g]<<24-8*(g%4);return new CryptoJS.lib.WordArray.init(e,
d)};a.equals=function(c,d){c=a.asUint8Array(c);d=a.asUint8Array(d);if(c.length!==d.length)return!1;for(var e=0;e<c.length;e++)if(c[e]!==d[e])return!1;return!0};return a}();var asn1={TAG_UNIVERSAL:0,TAG_APPLICATION:64,TAG_CONTEXT:128,TAG_PRIVATE:192,TAG_PRIMITIVE:0,TAG_CONSTRUCTED:32,Error:function(a){this.message=a}};asn1.Error.prototype.toString=function(){return"ASN.1 error: "+this.message};asn1.tag=function(a,c,b){void 0===c&&(c=asn1.TAG_CONTEXT);void 0===b&&(b=asn1.TAG_PRIMITIVE);if(31<=a)throw new asn1.Error("High-tag-number form not implemented!");return a|c|b};asn1.Buffer=function(){this.buffer=new Uint8Array(10);this.start=10};
asn1.Buffer.prototype.reserve=function(a){if(!(this.start>=a)){var c=a-this.start+this.buffer.byteLength;for(a=this.buffer.byteLength;a<c;)a*=2;c=new Uint8Array(a);c.set(this.buffer,a-this.buffer.byteLength);this.start+=a-this.buffer.byteLength;this.buffer=c}};asn1.Buffer.prototype.prependUint8=function(a){this.reserve(1);this.start-=1;this.buffer[this.start]=a;return 1};
asn1.Buffer.prototype.prependUint32=function(a,c){return c?this.prependBytes([a&255,a>>>8&255,a>>>16&255,a>>>24]):this.prependBytes([a>>>24,a>>>16&255,a>>>8&255,a&255])};asn1.Buffer.prototype.prependUint16=function(a,c){return c?this.prependBytes([a&255,a>>>8]):this.prependBytes([a>>>8,a&255])};asn1.Buffer.prototype.prependBytes=function(a){a instanceof Array||(a=arrayutils.asUint8Array(a));this.reserve(a.length);this.start-=a.length;this.buffer.set(a,this.start);return a.length};
asn1.Buffer.prototype.contents=function(){return this.buffer.subarray(this.start)};asn1.encodeTagDER=function(a,c){return c.prependUint8(a)};asn1.encodeLengthDER=function(a,c){if(127>=a)return c.prependUint8(a);for(var b=0;0<a;)c.prependUint8(a&255),a>>=8,b++;c.prependUint8(b|128);return b+1};
asn1.decodeTagLengthValueDER=function(a){var c=0,b=a[c],d=b&31,e=b&32,b=b&192;if(31==d)throw new asn1.Error("High-tag-number form not implemented!");d=asn1.tag(d,b,e);c++;b=a[c];e=0;c++;if(0==(b&128))e=b;else{if(128==b)throw new asn1.Error("Indefinite-length method unsupported!");for(var b=b&127,g=0;g<b;g++,c++)e*=256,e+=a[c]}if(c+e>a.length)throw new asn1.Error("Length too large!");return[d,a.subarray(c,c+e),a.subarray(c+e)]};
asn1.Type=function(a,c){(this.primitive=c?!0:!1)||(a|=asn1.TAG_CONSTRUCTED);this.tag=a};asn1.Type.prototype.encodeDER=function(a){var c=new asn1.Buffer;this.encodeDERTriple(a,c);return c.contents()};asn1.Type.prototype.encodeDERTriple=function(a,c){var b=this.encodeDERValue(a,c),b=b+asn1.encodeLengthDER(b,c);return b+=asn1.encodeTagDER(this.tag,c)};asn1.Type.prototype.decodeDER=function(a){a=this.decodeDERPrefix(a);var c=a[0];if(0!=a[1].byteLength)throw new asn1.Error("Excess data!");return c};
asn1.Type.prototype.decodeDERPrefix=function(a){a=new Uint8Array(a);a=asn1.decodeTagLengthValueDER(a);var c=a[1],b=a[2];if(a[0]!=this.tag)throw new asn1.Error("Tag mismatch!");return[this.decodeDERValue(c),b]};asn1.Type.prototype.tagged=function(a){return new asn1.ExplicitlyTagged(a,this)};asn1.Type.prototype.implicitlyTagged=function(a){return new asn1.ImplicitlyTagged(a,this)};
asn1.Type.prototype.constrained=function(a){var c=this.subtype(),b=this;c.encodeDERValue=function(c,e){a.call(this,c);return b.encodeDERValue(c,e)};c.decodeDERValue=function(c){c=b.decodeDERValue(c);a.call(this,c);return c};return c};asn1.Type.prototype.subtype=function(){return Object.create(this)};asn1.ExplicitlyTagged=function(a,c){asn1.Type.call(this,a,!1);this.baseType=c};asn1.ExplicitlyTagged.prototype=Object.create(asn1.Type.prototype);
asn1.ExplicitlyTagged.prototype.encodeDERValue=function(a,c){return this.baseType.encodeDERTriple(a,c)};asn1.ExplicitlyTagged.prototype.decodeDERValue=function(a){return this.baseType.decodeDER(a)};asn1.ImplicitlyTagged=function(a,c){asn1.Type.call(this,a,c.primitive);this.baseType=c};asn1.ImplicitlyTagged.prototype=Object.create(asn1.Type.prototype);asn1.ImplicitlyTagged.prototype.encodeDERValue=function(a,c){return this.baseType.encodeDERValue(a,c)};
asn1.ImplicitlyTagged.prototype.decodeDERValue=function(a){return this.baseType.decodeDERValue(a)};asn1.BOOLEAN=new asn1.Type(asn1.tag(1,asn1.TAG_UNIVERSAL),!0);asn1.BOOLEAN.encodeDERValue=function(a,c){if("boolean"!=typeof a)throw new TypeError("boolean");return c.prependUint8(a?255:0)};asn1.BOOLEAN.decodeDERValue=function(a){return 0!==a[0]};asn1.INTEGER=new asn1.Type(asn1.tag(2,asn1.TAG_UNIVERSAL),!0);
asn1.INTEGER.encodeDERValue=function(a,c){var b=0,d;if("number"!=typeof a)throw new TypeError("Not a number");do d=a&255,b+=c.prependUint8(d),d=d&128?-1:0,a>>=8;while(a!==d);return b};asn1.INTEGER.decodeDERValue=function(a){var c=a[0];127<c&&(c-=256);for(var b=1;b<a.length;b++)c*=256,c+=a[b];return c};
asn1.INTEGER.valueConstrained=function(){for(var a=[],c=0;c<arguments.length;c++)a.push(arguments[c]);return this.constrained(function(c){if(-1==a.indexOf(c))throw new RangeError("Invalid value: "+c);})};asn1.INTEGER.rangeConstrained=function(a,c){return this.constrained(function(b){if(b<a||b>c)throw new RangeError("Invalid value: "+b);})};asn1.BIT_STRING=new asn1.Type(asn1.tag(3,asn1.TAG_UNIVERSAL),!0);
asn1.BIT_STRING.encodeDERValue=function(a,c){var b=8-a.length%8;8==b&&(b=0);for(var d=0,e=a.length+b-8;0<=e;e-=8){for(var g=0,p=0;8>p;p++)g|=(a[e+p]||0)<<7-p;d+=c.prependUint8(g)}return d+=c.prependUint8(b)};asn1.BIT_STRING.decodeDERValue=function(a){for(var c=a[0],b=[],d=1;d<a.length;d++)for(var e=a[d],g=7;0<=g;g--)b.push(e&1<<g?1:0);return b.slice(0,b.length-c)};asn1.OCTET_STRING=new asn1.Type(asn1.tag(4,asn1.TAG_UNIVERSAL),!0);
asn1.OCTET_STRING.encodeDERValue=function(a,c){if("undefined"!==typeof ArrayBufferView&&!a instanceof ArrayBufferView)throw new TypeError("Not an array buffer");return c.prependBytes(a)};asn1.OCTET_STRING.decodeDERValue=function(a){return new Uint8Array(a)};asn1.NULL=new asn1.Type(asn1.tag(5,asn1.TAG_UNIVERSAL),!0);asn1.NULL.encodeDERValue=function(a,c){if(null!==a)throw new TypeError("Bad value");return 0};asn1.NULL.decodeDERValue=function(a){if(0<a.length)throw new asn1.Error("Bad encoding");return null};
asn1.OBJECT_IDENTIFIER=new asn1.Type(asn1.tag(6,asn1.TAG_UNIVERSAL),!0);asn1.OBJECT_IDENTIFIER.encodeDERValue=function(a,c){if("string"!==typeof a)throw new TypeError("Not a string");var b=a.split(".");if(2>b.length)throw new TypeError("Too few components");for(var d=[40*Number(b[0])+Number(b[1])],e=2;e<b.length;e++)d.push(Number(b[e]));b=0;for(e=d.length-1;0<=e;e--)for(var g=d[e],b=b+c.prependUint8(g&127),g=g>>>7;0<g;)b+=c.prependUint8(g&127|128),g>>>=7;return b};
asn1.OBJECT_IDENTIFIER.decodeDERValue=function(a){for(var c=0,b=[],d=0;d<a.length;d++){var e=a[d],c=128*c,c=c+(e&127);e&128||(b.push(c),c=0)}if(0===b.length)throw new asn1.Error("Bad format");a=[];a=Math.min(b[0]/40>>>0,2);a=[a,b[0]-40*a];a=a.concat(b.slice(1));return a.join(".")};asn1.GeneralString=new asn1.Type(asn1.tag(27,asn1.TAG_UNIVERSAL),!0);asn1.GeneralString.encodeDERValue=function(a,c){if("string"!=typeof a)throw new TypeError("Not a string");return c.prependBytes(arrayutils.fromString(a))};
asn1.GeneralString.decodeDERValue=function(a){try{return arrayutils.toString(a)}catch(c){if(c instanceof URIError)throw new asn1.Error("Invalid UTF-8 string");throw c;}};asn1.GeneralizedTime=new asn1.Type(asn1.tag(24,asn1.TAG_UNIVERSAL),!0);
asn1.GeneralizedTime.encodeDERValue=function(a,c){function b(a,c){void 0==c&&(c=2);for(var b=String(a);b.length<c;)b="0"+b;return b}var d=a.getUTCFullYear()+b(a.getUTCMonth()+1)+b(a.getUTCDate())+b(a.getUTCHours())+b(a.getUTCMinutes())+b(a.getUTCSeconds());if(0!=a.getUTCMilliseconds()){for(var e=b(a.getUTCMilliseconds(),3);"0"==e[e.length-1];)e=e.substr(0,e.length-1);d+="."+e}return c.prependBytes(arrayutils.fromByteString(d+"Z"))};
asn1.GeneralizedTime.decodeDERValue=function(a){var c=arrayutils.toByteString(a).match(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(\.(\d{1,3}))?Z$/);if(!c)throw new asn1.Error("Bad date format");a=new Date(Date.UTC(Number(c[1]),Number(c[2])-1,Number(c[3]),Number(c[4]),Number(c[5]),Number(c[6])));if(c[8]){for(c=c[8];3>c.length;)c+="0";a.setUTCMilliseconds(Number(c))}return a};asn1.SEQUENCE_OF=function(a){asn1.Type.call(this,asn1.tag(16,asn1.TAG_UNIVERSAL),!1);this.componentType=a};
asn1.SEQUENCE_OF.prototype=Object.create(asn1.Type.prototype);asn1.SEQUENCE_OF.prototype.encodeDERValue=function(a,c){for(var b=0,d=a.length-1;0<=d;d--)b+=this.componentType.encodeDERTriple(a[d],c);return b};asn1.SEQUENCE_OF.prototype.decodeDERValue=function(a){for(var c=[];a.length;)a=this.componentType.decodeDERPrefix(a),c.push(a[0]),a=a[1];return c};asn1.SEQUENCE=function(a){asn1.Type.call(this,asn1.tag(16,asn1.TAG_UNIVERSAL),!1);this.componentSpec=a};asn1.SEQUENCE.prototype=Object.create(asn1.Type.prototype);
asn1.SEQUENCE.prototype.encodeDERValue=function(a,c){for(var b=0,d=this.componentSpec.length-1;0<=d;d--){var e=this.componentSpec[d].id;if(e in a)b+=this.componentSpec[d].type.encodeDERTriple(a[e],c);else if(!this.componentSpec[d].optional)throw new TypeError("Field "+e+" missing!");}return b};
asn1.SEQUENCE.prototype.decodeDERValue=function(a){for(var c={},b=0;a.length;){var d=asn1.decodeTagLengthValueDER(a);a=d[0];for(var e=d[1],d=d[2];b<this.componentSpec.length&&this.componentSpec[b].type.tag!=a;){if(!this.componentSpec[b].optional)throw new asn1.Error("Missing required field "+this.componentSpec[b].id);b++}if(b>=this.componentSpec.length)throw new asn1.Error("Unexpected tag "+a);c[this.componentSpec[b].id]=this.componentSpec[b].type.decodeDERValue(e);a=d;b++}for(;b<this.componentSpec.length;){if(!this.componentSpec[b].optional)throw new asn1.Error("Missing required field "+
this.componentSpec[b].id);b++}return c};asn1.CHOICE=function(a){this.choices=a};asn1.CHOICE.prototype=Object.create(asn1.Type.prototype);asn1.CHOICE.prototype.encodeDERTriple=function(a,c){var b=a[0],d=a[1];if(-1==this.choices.indexOf(b))throw new TypeError("Invalid type");return b.encodeDERTriple(d,c)};
asn1.CHOICE.prototype.decodeDERPrefix=function(a){var c=asn1.decodeTagLengthValueDER(a);a=c[0];for(var b=c[1],c=c[2],d=0;d<this.choices.length;d++)if(a==this.choices[d].tag)return[[this.choices[d],this.choices[d].decodeDERValue(b)],c];throw new asn1.Error("Unexpected tag "+a);};"object"===typeof exports&&(module.exports=asn1);"undefined"===typeof asn1&&"function"===typeof require&&(asn1=require("./asn1.js"));var krb={};krb.KerberosString=asn1.GeneralString;krb.Int32=asn1.INTEGER.rangeConstrained(-2147483648,2147483647);krb.UInt32=asn1.INTEGER.rangeConstrained(0,4294967295);krb.Microseconds=asn1.INTEGER.rangeConstrained(0,999999);krb.Realm=krb.KerberosString;krb.PrincipalName=new asn1.SEQUENCE([{id:"nameType",type:krb.Int32.tagged(asn1.tag(0))},{id:"nameString",type:(new asn1.SEQUENCE_OF(krb.KerberosString)).tagged(asn1.tag(1))}]);
krb.principalNamesEqual=function(a,c){if(a.nameString.length!=c.nameString.length)return!1;for(var b=0;b<a.nameString.length;b++)if(a.nameString[b]!=c.nameString[b])return!1;return!0};krb.KerberosTime=asn1.GeneralizedTime.constrained(function(a){if(0!=a.getUTCMilliseconds())throw"Milliseconds not allowed in KerberosTime";});krb.HostAddress=new asn1.SEQUENCE([{id:"addrType",type:krb.Int32.tagged(asn1.tag(0))},{id:"address",type:asn1.OCTET_STRING.tagged(asn1.tag(1))}]);krb.HostAddresses=new asn1.SEQUENCE_OF(krb.HostAddress);
krb.AuthorizationData=new asn1.SEQUENCE_OF(new asn1.SEQUENCE([{id:"adType",type:krb.Int32.tagged(asn1.tag(0))},{id:"adData",type:asn1.OCTET_STRING.tagged(asn1.tag(1))}]));krb.AD_IF_RELEVANT=krb.AuthorizationData;krb.EncryptedData=new asn1.SEQUENCE([{id:"etype",type:krb.Int32.tagged(asn1.tag(0))},{id:"kvno",type:krb.UInt32.tagged(asn1.tag(1)),optional:!0},{id:"cipher",type:asn1.OCTET_STRING.tagged(asn1.tag(2))}]);
krb.EncryptionKey=new asn1.SEQUENCE([{id:"keytype",type:krb.Int32.tagged(asn1.tag(0))},{id:"keyvalue",type:asn1.OCTET_STRING.tagged(asn1.tag(1))}]);krb.Checksum=new asn1.SEQUENCE([{id:"cksumtype",type:krb.Int32.tagged(asn1.tag(0))},{id:"checksum",type:asn1.OCTET_STRING.tagged(asn1.tag(1))}]);
krb.AD_KDCIssued=new asn1.SEQUENCE([{id:"adChecksum",type:krb.Checksum.tagged(asn1.tag(0))},{id:"iRealm",type:krb.Realm.tagged(asn1.tag(1)),optional:!0},{id:"iSname",type:krb.PrincipalName.tagged(asn1.tag(2)),optional:!0},{id:"elements",type:krb.AuthorizationData.tagged(asn1.tag(3))}]);krb.AD_AND_OR=new asn1.SEQUENCE([{id:"conditionCount",type:krb.Int32.tagged(asn1.tag(0))},{id:"elements",type:krb.AuthorizationData.tagged(asn1.tag(1))}]);krb.AD_MANDATORY_FOR_KDC=krb.AuthorizationData;
krb.PA_DATA=new asn1.SEQUENCE([{id:"padataType",type:krb.Int32.tagged(asn1.tag(1))},{id:"padataValue",type:asn1.OCTET_STRING.tagged(asn1.tag(2))}]);krb.ENC_TIMESTAMP=krb.EncryptedData;krb.ENC_TS_ENC=new asn1.SEQUENCE([{id:"patimestamp",type:krb.KerberosTime.tagged(asn1.tag(0))},{id:"pausec",type:krb.Microseconds.tagged(asn1.tag(1)),optional:!0}]);krb.ETYPE_INFO_ENTRY=new asn1.SEQUENCE([{id:"etype",type:krb.Int32.tagged(asn1.tag(0))},{id:"salt",type:asn1.OCTET_STRING.tagged(asn1.tag(1)),optional:!0}]);
krb.ETYPE_INFO=new asn1.SEQUENCE_OF(krb.ETYPE_INFO_ENTRY);krb.ETYPE_INFO2_ENTRY=new asn1.SEQUENCE([{id:"etype",type:krb.Int32.tagged(asn1.tag(0))},{id:"salt",type:krb.KerberosString.tagged(asn1.tag(1)),optional:!0},{id:"s2kparams",type:asn1.OCTET_STRING.tagged(asn1.tag(2)),optional:!0}]);krb.ETYPE_INFO2=new asn1.SEQUENCE_OF(krb.ETYPE_INFO2_ENTRY);krb.KerberosFlags=asn1.BIT_STRING.constrained(function(a){if(32>a.length)throw"Invalid KerberosFlags";});
krb.KerberosFlags.makeZeroFlags=function(a){a=a||32;for(var c=[],b=0;b<a;b++)c.push(0);return c};krb.KerberosFlags.make=function(){for(var a=32,c=0;c<arguments.length;c++)a=Math.max(a,arguments[c]);a=this.makeZeroFlags(a);for(c=0;c<arguments.length;c++)a[arguments[c]]=1;return a};
krb.Ticket=(new asn1.SEQUENCE([{id:"tktVno",type:asn1.INTEGER.valueConstrained(5).tagged(asn1.tag(0))},{id:"realm",type:krb.Realm.tagged(asn1.tag(1))},{id:"sname",type:krb.PrincipalName.tagged(asn1.tag(2))},{id:"encPart",type:krb.EncryptedData.tagged(asn1.tag(3))}])).tagged(asn1.tag(1,asn1.TAG_APPLICATION));krb.TicketFlags=krb.KerberosFlags.subtype();krb.TicketFlags.reserved=0;krb.TicketFlags.forwardable=1;krb.TicketFlags.forwarded=2;krb.TicketFlags.proxiable=3;krb.TicketFlags.proxy=4;
krb.TicketFlags.may_postdate=5;krb.TicketFlags.postdated=6;krb.TicketFlags.invalid=7;krb.TicketFlags.renewable=8;krb.TicketFlags.initial=9;krb.TicketFlags.pre_authent=10;krb.TicketFlags.hw_authent=11;krb.TicketFlags.transited_policy_checked=12;krb.TicketFlags.ok_as_delegate=13;krb.TransitedEncoding=new asn1.SEQUENCE([{id:"trType",type:krb.Int32.tagged(asn1.tag(0))},{id:"contents",type:asn1.OCTET_STRING.tagged(asn1.tag(1))}]);
krb.EncTicketPart=(new asn1.SEQUENCE([{id:"flags",type:krb.TicketFlags.tagged(asn1.tag(0))},{id:"key",type:krb.EncryptionKey.tagged(asn1.tag(1))},{id:"crealm",type:krb.Realm.tagged(asn1.tag(2))},{id:"cname",type:krb.PrincipalName.tagged(asn1.tag(3))},{id:"transited",type:krb.TransitedEncoding.tagged(asn1.tag(4))},{id:"authtime",type:krb.KerberosTime.tagged(asn1.tag(5))},{id:"starttime",type:krb.KerberosTime.tagged(asn1.tag(6)),optional:!0},{id:"endtime",type:krb.KerberosTime.tagged(asn1.tag(7))},
{id:"renewTill",type:krb.KerberosTime.tagged(asn1.tag(8)),optional:!0},{id:"caddr",type:krb.HostAddresses.tagged(asn1.tag(9)),optional:!0},{id:"authorizationData",type:krb.AuthorizationData.tagged(asn1.tag(10)),optional:!0}])).tagged(asn1.tag(3,asn1.TAG_APPLICATION));
krb.KRB_ERROR=(new asn1.SEQUENCE([{id:"pvno",type:asn1.INTEGER.valueConstrained(5).tagged(asn1.tag(0))},{id:"msgType",type:asn1.INTEGER.valueConstrained(30).tagged(asn1.tag(1))},{id:"ctime",type:krb.KerberosTime.tagged(asn1.tag(2)),optional:!0},{id:"cusec",type:krb.Microseconds.tagged(asn1.tag(3)),optional:!0},{id:"stime",type:krb.KerberosTime.tagged(asn1.tag(4))},{id:"susec",type:krb.Microseconds.tagged(asn1.tag(5))},{id:"errorCode",type:krb.Int32.tagged(asn1.tag(6))},{id:"crealm",type:krb.Realm.tagged(asn1.tag(7)),
optional:!0},{id:"cname",type:krb.PrincipalName.tagged(asn1.tag(8)),optional:!0},{id:"realm",type:krb.Realm.tagged(asn1.tag(9))},{id:"sname",type:krb.PrincipalName.tagged(asn1.tag(10))},{id:"eText",type:krb.KerberosString.tagged(asn1.tag(11)),optional:!0},{id:"eData",type:asn1.OCTET_STRING.tagged(asn1.tag(12)),optional:!0}])).tagged(asn1.tag(30,asn1.TAG_APPLICATION));krb.METHOD_DATA=new asn1.SEQUENCE_OF(krb.PA_DATA);
krb.TYPED_DATA=new asn1.SEQUENCE([{id:"dataType",type:krb.Int32.tagged(asn1.tag(0))},{id:"dataValue",type:asn1.OCTET_STRING.tagged(asn1.tag(1)),optional:!0}]);krb.KDCOptions=krb.KerberosFlags.subtype();krb.KDCOptions.reserved=0;krb.KDCOptions.forwardable=1;krb.KDCOptions.forwarded=2;krb.KDCOptions.proxiable=3;krb.KDCOptions.proxy=4;krb.KDCOptions.allow_postdate=5;krb.KDCOptions.postdated=6;krb.KDCOptions.renewable=8;krb.KDCOptions.opt_hardware_auth=11;krb.KDCOptions.disable_transited_check=26;
krb.KDCOptions.renewable_ok=27;krb.KDCOptions.enc_tkt_in_skey=28;krb.KDCOptions.renew=30;krb.KDCOptions.validate=31;
krb.KDC_REQ_BODY=new asn1.SEQUENCE([{id:"kdcOptions",type:krb.KDCOptions.tagged(asn1.tag(0))},{id:"principalName",type:krb.PrincipalName.tagged(asn1.tag(1)),optional:!0},{id:"realm",type:krb.Realm.tagged(asn1.tag(2))},{id:"sname",type:krb.PrincipalName.tagged(asn1.tag(3)),optional:!0},{id:"from",type:krb.KerberosTime.tagged(asn1.tag(4)),optional:!0},{id:"till",type:krb.KerberosTime.tagged(asn1.tag(5))},{id:"rtime",type:krb.KerberosTime.tagged(asn1.tag(6)),optional:!0},{id:"nonce",type:krb.UInt32.tagged(asn1.tag(7))},
{id:"etype",type:(new asn1.SEQUENCE_OF(krb.Int32)).tagged(asn1.tag(8))},{id:"addresses",type:krb.HostAddresses.tagged(asn1.tag(9)),optional:!0},{id:"encAuthorizationData",type:krb.EncryptedData.tagged(asn1.tag(10)),optional:!0},{id:"additionalTickets",type:(new asn1.SEQUENCE_OF(krb.Ticket)).tagged(asn1.tag(10)),optional:!0}]);
krb.KDC_REQ=new asn1.SEQUENCE([{id:"pvno",type:asn1.INTEGER.valueConstrained(5).tagged(asn1.tag(1))},{id:"msgType",type:asn1.INTEGER.valueConstrained(10,12).tagged(asn1.tag(2))},{id:"padata",type:(new asn1.SEQUENCE_OF(krb.PA_DATA)).tagged(asn1.tag(3)),optional:!0},{id:"reqBody",type:krb.KDC_REQ_BODY.tagged(asn1.tag(4))}]);krb.AS_REQ=krb.KDC_REQ.tagged(asn1.tag(10,asn1.TAG_APPLICATION));krb.TGS_REQ=krb.KDC_REQ.tagged(asn1.tag(12,asn1.TAG_APPLICATION));
krb.KDC_REP=new asn1.SEQUENCE([{id:"pvno",type:asn1.INTEGER.valueConstrained(5).tagged(asn1.tag(0))},{id:"msgType",type:asn1.INTEGER.valueConstrained(11,13).tagged(asn1.tag(1))},{id:"padata",type:(new asn1.SEQUENCE_OF(krb.PA_DATA)).tagged(asn1.tag(2)),optional:!0},{id:"crealm",type:krb.Realm.tagged(asn1.tag(3))},{id:"cname",type:krb.PrincipalName.tagged(asn1.tag(4))},{id:"ticket",type:krb.Ticket.tagged(asn1.tag(5))},{id:"encPart",type:krb.EncryptedData.tagged(asn1.tag(6))}]);
krb.AS_REP=krb.KDC_REP.tagged(asn1.tag(11,asn1.TAG_APPLICATION));krb.TGS_REP=krb.KDC_REP.tagged(asn1.tag(13,asn1.TAG_APPLICATION));krb.AS_REP_OR_ERROR=new asn1.CHOICE([krb.AS_REP,krb.KRB_ERROR]);krb.TGS_REP_OR_ERROR=new asn1.CHOICE([krb.TGS_REP,krb.KRB_ERROR]);krb.LastReq=new asn1.SEQUENCE_OF(new asn1.SEQUENCE([{id:"lrType",type:krb.Int32.tagged(asn1.tag(0))},{id:"lrValue",type:krb.KerberosTime.tagged(asn1.tag(1))}]));
krb.EncKDCRepPart=new asn1.SEQUENCE([{id:"key",type:krb.EncryptionKey.tagged(asn1.tag(0))},{id:"lastReq",type:krb.LastReq.tagged(asn1.tag(1))},{id:"nonce",type:krb.UInt32.tagged(asn1.tag(2))},{id:"keyExpiration",type:krb.KerberosTime.tagged(asn1.tag(3)),optional:!0},{id:"flags",type:krb.TicketFlags.tagged(asn1.tag(4))},{id:"authtime",type:krb.KerberosTime.tagged(asn1.tag(5))},{id:"starttime",type:krb.KerberosTime.tagged(asn1.tag(6)),optional:!0},{id:"endtime",type:krb.KerberosTime.tagged(asn1.tag(7))},
{id:"renewTill",type:krb.KerberosTime.tagged(asn1.tag(8)),optional:!0},{id:"srealm",type:krb.Realm.tagged(asn1.tag(9))},{id:"sname",type:krb.PrincipalName.tagged(asn1.tag(10))},{id:"caddr",type:krb.HostAddresses.tagged(asn1.tag(11)),optional:!0}]);krb.EncASRepPart=krb.EncKDCRepPart.tagged(asn1.tag(25,asn1.TAG_APPLICATION));krb.EncTGSRepPart=krb.EncKDCRepPart.tagged(asn1.tag(26,asn1.TAG_APPLICATION));krb.EncASorTGSRepPart=new asn1.CHOICE([krb.EncASRepPart,krb.EncTGSRepPart]);krb.APOptions=krb.KerberosFlags.subtype();
krb.APOptions.use_session_key=1;krb.APOptions.mutual_required=2;krb.AP_REQ=(new asn1.SEQUENCE([{id:"pvno",type:asn1.INTEGER.valueConstrained(5).tagged(asn1.tag(0))},{id:"msgType",type:asn1.INTEGER.valueConstrained(14).tagged(asn1.tag(1))},{id:"apOptions",type:krb.APOptions.tagged(asn1.tag(2))},{id:"ticket",type:krb.Ticket.tagged(asn1.tag(3))},{id:"authenticator",type:krb.EncryptedData.tagged(asn1.tag(4))}])).tagged(asn1.tag(14,asn1.TAG_APPLICATION));
krb.Authenticator=(new asn1.SEQUENCE([{id:"authenticatorVno",type:asn1.INTEGER.valueConstrained(5).tagged(asn1.tag(0))},{id:"crealm",type:krb.Realm.tagged(asn1.tag(1))},{id:"cname",type:krb.PrincipalName.tagged(asn1.tag(2))},{id:"cksum",type:krb.Checksum.tagged(asn1.tag(3)),optional:!0},{id:"cusec",type:krb.Microseconds.tagged(asn1.tag(4))},{id:"ctime",type:krb.KerberosTime.tagged(asn1.tag(5))},{id:"subkey",type:krb.EncryptionKey.tagged(asn1.tag(6)),optional:!0},{id:"seqNumber",type:krb.UInt32.tagged(asn1.tag(7)),
optional:!0},{id:"authorizationData",type:krb.AuthorizationData.tagged(asn1.tag(8)),optional:!0}])).tagged(asn1.tag(2,asn1.TAG_APPLICATION));krb.AP_REP=(new asn1.SEQUENCE([{id:"pvno",type:asn1.INTEGER.valueConstrained(5).tagged(asn1.tag(0))},{id:"msgType",type:asn1.INTEGER.valueConstrained(15).tagged(asn1.tag(1))},{id:"encPart",type:krb.EncryptedData.tagged(asn1.tag(2))}])).tagged(asn1.tag(15,asn1.TAG_APPLICATION));
krb.EncAPRepPart=(new asn1.SEQUENCE([{id:"ctime",type:krb.KerberosTime.tagged(asn1.tag(0))},{id:"cusec",type:krb.Microseconds.tagged(asn1.tag(1))},{id:"subkey",type:krb.EncryptionKey.tagged(asn1.tag(2)),optional:!0},{id:"seqNumber",type:krb.UInt32.tagged(asn1.tag(3)),optional:!0}])).tagged(asn1.tag(27,asn1.TAG_APPLICATION));krb.EtypeList=new asn1.SEQUENCE_OF(krb.Int32);krb.KU_AS_REQ_PA_ENC_TIMESTAMP=1;krb.KU_KDC_REP_TICKET=2;krb.KU_AS_REQ_ENC_PART=3;krb.KU_TGS_REQ_BODY_AUTH_DATA=4;
krb.KU_TGS_REQ_BODY_AUTH_DATA_SUBKEY=5;krb.KU_TGS_REQ_PA_TGS_REQ_CKSUM=6;krb.KU_TGS_REQ_PA_TGS_REQ=7;krb.KU_TGS_REQ_ENC_PART=8;krb.KU_TGS_REQ_ENC_PART_SUBKEY=9;krb.KU_AP_REQ_AUTHENTICATOR_CKSUM=10;krb.KU_AP_REQ_AUTHENTICATOR=11;krb.KU_AP_REP_ENC_PART=12;krb.KU_KRB_PRIV_ENC_PART=13;krb.KU_KRB_CRED_ENC_PART=14;krb.KU_KRB_SAFE_CKSUM=15;krb.KU_AD_KDC_ISSUED_CKSUM=19;krb.KU_GENERIC_ENC=1024;krb.KU_GENERIC_CKSUM=1025;krb.PA_TGS_REQ=1;krb.PA_ENC_TIMESTAMP=2;krb.PA_PW_SALT=3;krb.PA_ENC_UNIX_TIME=5;
krb.PA_SANDIA_SECUREID=6;krb.PA_SESAME=7;krb.PA_OSF_DCE=8;krb.PA_CYBERSAFE_SECUREID=9;krb.PA_AFS3_SALT=10;krb.PA_ETYPE_INFO=11;krb.PA_SAM_CHALLENGE=12;krb.PA_SAM_RESPONSE=13;krb.PA_PK_AS_REQ_OLD=14;krb.PA_PK_AS_REP_OLD=15;krb.PA_PK_AS_REQ=16;krb.PA_PK_AS_REP=17;krb.PA_ETYPE_INFO2=19;krb.PA_USE_SPECIFIED_KVNO=20;krb.PA_SAM_REDIRECT=21;krb.PA_GET_FROM_TYPED_DATA=22;krb.TD_PADATA=22;krb.PA_SAM_ETYPE_INFO=23;krb.PA_ALT_PRINC=24;krb.PA_SAM_CHALLENGE2=30;krb.PA_SAM_RESPONSE2=31;krb.PA_EXTRA_TGT=41;
krb.TD_PKINIT_CMS_CERTIFICATES=101;krb.TD_KRB_PRINCIPAL=102;krb.TD_KRB_REALM=103;krb.TD_TRUSTED_CERTIFIERS=104;krb.TD_CERTIFICATE_INDEX=105;krb.TD_APP_DEFINED_ERROR=106;krb.TD_REQ_NONCE=107;krb.TD_REQ_SEQ=108;krb.PA_PAC_REQUEST=128;krb.ADDRESS_IPV4=2;krb.ADDRESS_DIRECTIONAL=3;krb.ADDRESS_CHAOSNET=5;krb.ADDRESS_XNS=6;krb.ADDRESS_ISO=7;krb.ADDRESS_DECNET_PHASE_IV=12;krb.ADDRESS_APPLETALK_UDP=16;krb.ADDRESS_NETBIOS=20;krb.ADDRESS_IPV6=24;krb.AD_IF_RELEVANT_TYPE=1;krb.AD_INTENDED_FOR_SERVER=2;
krb.AD_INTENDED_FOR_APPLICATION_CLASS=3;krb.AD_KDC_ISSUED=4;krb.AD_AND_OR=5;krb.AD_MANDATORY_TICKET_EXTENSIONS=6;krb.AD_IN_TICKET_EXTENSIONS=7;krb.AD_MANDATORY_FOR_KDC=8;krb.OSF_DCE=64;krb.SESAME=65;krb.AD_OSF_DCE_PKI_CERTID=66;krb.AD_WIN2K_PAC=128;krb.AD_ETYPE_NEGOTIATION=129;krb.DOMAIN_X500_COMPRESS=1;krb.pvno=5;krb.KRB_MT_AS_REQ=10;krb.KRB_MT_AS_REP=11;krb.KRB_MT_TGS_REQ=12;krb.KRB_MT_TGS_REP=13;krb.KRB_MT_AP_REQ=14;krb.KRB_MT_AP_REP=15;krb.KRB_MT_SAFE=20;krb.KRB_MT_PRIV=21;krb.KRB_MT_CRED=22;
krb.KRB_MT_ERROR=30;krb.KRB_NT_UNKNOWN=0;krb.KRB_NT_PRINCIPAL=1;krb.KRB_NT_SRV_INST=2;krb.KRB_NT_SRV_HST=3;krb.KRB_NT_SRV_XHST=4;krb.KRB_NT_UID=5;krb.KRB_NT_X500_PRINCIPAL=6;krb.KRB_NT_SMTP_NAME=7;krb.KRB_NT_ENTERPRISE=10;krb.KDC_ERR_NONE=0;krb.KDC_ERR_NAME_EXP=1;krb.KDC_ERR_SERVICE_EXP=2;krb.KDC_ERR_BAD_PVNO=3;krb.KDC_ERR_C_OLD_MAST_KVNO=4;krb.KDC_ERR_S_OLD_MAST_KVNO=5;krb.KDC_ERR_C_PRINCIPAL_UNKNOWN=6;krb.KDC_ERR_S_PRINCIPAL_UNKNOWN=7;krb.KDC_ERR_PRINCIPAL_NOT_UNIQUE=8;krb.KDC_ERR_NULL_KEY=9;
krb.KDC_ERR_CANNOT_POSTDATE=10;krb.KDC_ERR_NEVER_VALID=11;krb.KDC_ERR_POLICY=12;krb.KDC_ERR_BADOPTION=13;krb.KDC_ERR_ETYPE_NOSUPP=14;krb.KDC_ERR_SUMTYPE_NOSUPP=15;krb.KDC_ERR_PADATA_TYPE_NOSUPP=16;krb.KDC_ERR_TRTYPE_NOSUPP=17;krb.KDC_ERR_CLIENT_REVOKED=18;krb.KDC_ERR_SERVICE_REVOKED=19;krb.KDC_ERR_TGT_REVOKED=20;krb.KDC_ERR_CLIENT_NOTYET=21;krb.KDC_ERR_SERVICE_NOTYET=22;krb.KDC_ERR_KEY_EXPIRED=23;krb.KDC_ERR_PREAUTH_FAILED=24;krb.KDC_ERR_PREAUTH_REQUIRED=25;krb.KDC_ERR_SERVER_NOMATCH=26;
krb.KDC_ERR_MUST_USE_USER2USER=27;krb.KDC_ERR_PATH_NOT_ACCEPTED=28;krb.KDC_ERR_SVC_UNAVAILABLE=29;krb.KRB_AP_ERR_BAD_INTEGRITY=31;krb.KRB_AP_ERR_TKT_EXPIRED=32;krb.KRB_AP_ERR_TKT_NYV=33;krb.KRB_AP_ERR_REPEAT=34;krb.KRB_AP_ERR_NOT_US=35;krb.KRB_AP_ERR_BADMATCH=36;krb.KRB_AP_ERR_SKEW=37;krb.KRB_AP_ERR_BADADDR=38;krb.KRB_AP_ERR_BADVERSION=39;krb.KRB_AP_ERR_MSG_TYPE=40;krb.KRB_AP_ERR_MODIFIED=41;krb.KRB_AP_ERR_BADORDER=42;krb.KRB_AP_ERR_BADKEYVER=44;krb.KRB_AP_ERR_NOKEY=45;krb.KRB_AP_ERR_MUT_FAIL=46;
krb.KRB_AP_ERR_BADDIRECTION=47;krb.KRB_AP_ERR_METHOD=48;krb.KRB_AP_ERR_BADSEQ=49;krb.KRB_AP_ERR_INAPP_CKSUM=50;krb.KRB_AP_PATH_NOT_ACCEPTED=51;krb.KRB_ERR_RESPONSE_TOO_BIG=52;krb.KRB_ERR_GENERIC=60;krb.KRB_ERR_FIELD_TOOLONG=61;krb.KDC_ERROR_CLIENT_NOT_TRUSTED=62;krb.KDC_ERROR_KDC_NOT_TRUSTED=63;krb.KDC_ERROR_INVALID_SIG=64;krb.KDC_ERR_KEY_TOO_WEAK=65;krb.KDC_ERR_CERTIFICATE_MISMATCH=66;krb.KRB_AP_ERR_NO_TGT=67;krb.KDC_ERR_WRONG_REALM=68;krb.KRB_AP_ERR_USER_TO_USER_REQUIRED=69;
krb.KDC_ERR_CANT_VERIFY_CERTIFICATE=70;krb.KDC_ERR_INVALID_CERTIFICATE=71;krb.KDC_ERR_REVOKED_CERTIFICATE=72;krb.KDC_ERR_REVOCATION_STATUS_UNKNOWN=73;krb.KDC_ERR_REVOCATION_STATUS_UNAVAILABLE=74;krb.KDC_ERR_CLIENT_NAME_MISMATCH=75;krb.KDC_ERR_KDC_NAME_MISMATCH=76;"object"===typeof exports&&(module.exports=krb);var kcrypto=function(){function a(a){for(a[a.length-1]>>>=0;4>a.length;)a.push(0)}function c(a,c){return[a[0]^c[0],a[1]^c[1],a[2]^c[2],a[3]^c[3]]}function b(a,c){var b=arrayutils.toSJCL(c),d=sjcl.bitArray.bitLength(b),e=a,f=d,g;f<e&&(g=e,e=f,f=g);for(;0!=e;)g=f%e,f=e,e=g;var e=a/f,f=13%d,q=arrayutils.toSJCL(new Uint8Array(a/8));g=[];for(var r=0,C=0;C<e;C++)for(g=sjcl.bitArray.concat(g,b),r+=d,b=sjcl.bitArray.concat(sjcl.bitArray.bitSlice(b,d-f),sjcl.bitArray.bitSlice(b,0,d-f));r>=a;){var n=q,q=sjcl.bitArray.bitSlice(g,
0,a);if(sjcl.bitArray.bitLength(n)!=sjcl.bitArray.bitLength(q))throw"Lengths must match";if(0==n.length)q=[];else{var p=sjcl.bitArray.getPartial(n[n.length-1]),s=0,n=n.slice(0),s=s+((n[n.length-1]>>>0)+(q[n.length-1]>>>0));n[n.length-1]=sjcl.bitArray.partial(p,s>>>0,1);for(var s=4294967296<s?1:0,t=n.length-2;0<=t;t--)s+=(n[t]>>>0)+(q[t]>>>0),n[t]=s>>>0,s=4294967296<=s?1:0;if(0<s&&(s=(1<<32-p)+(n[n.length-1]>>>0),n[n.length-1]=sjcl.bitArray.partial(p,s>>>0,1),4294967296<=s))for(t=n.length-2;0<=t&&
!(s=1+(n[t]>>>0),n[t]=s>>>0,4294967296>s);t--);q=n}g=sjcl.bitArray.bitSlice(g,a);r-=a}if(0!=sjcl.bitArray.bitLength(g))throw"Bits left over!";return arrayutils.fromSJCL(q)}function d(a){function c(b,d){var e=b.encrypt(arrayutils.toSJCL(d)),e=sjcl.bitArray.bitSlice(e,0,8*a.hmacOutputSize);return arrayutils.fromSJCL(e)}if(0!=a.keyGenerationSeedLength%8)throw"Bad simple profile";var d={};d.enctype=a.enctype;var e=new Uint8Array(a.cipherBlockSize);d.initialCipherState=function(){return e};d.keyGenerationSeedLength=
a.keyGenerationSeedLength;d.randomToKey=function(c){return a.randomToKey(c)};d.stringToKey=function(c,b,d){return a.stringToKey(c,b,d,this)};d.encrypt=function(b,d,e){e=arrayutils.asUint8Array(e);var f=arrayutils.fromSJCL(sjcl.bitArray.clamp(sjcl.random.randomWords(Math.ceil(a.cipherBlockSize/4)),8*a.cipherBlockSize)),h=(a.cipherBlockSize+e.length)%a.messageBlockSize,h=a.messageBlockSize-h;h==a.messageBlockSize&&(h=0);h=new Uint8Array(f.length+e.length+h);h.set(f);h.set(e,f.length);e=a.encrypt(b.E,
d,h,this);d=e[0];e=e[1];b=c(b.I,h);h=new Uint8Array(e.length+b.length);h.set(e);h.set(b,e.length);return[d,h]};d.decrypt=function(b,d,e){e=arrayutils.asUint8Array(e);var h=e.subarray(0,e.length-a.hmacOutputSize);e=e.subarray(e.length-a.hmacOutputSize);h=a.decrypt(b.E,d,h,this);d=h[0];h=h[1];if(!arrayutils.equals(e,c(b.I,h)))throw new f.DecryptionError("Checksum mismatch!");h=h.subarray(a.cipherBlockSize);return[d,h]};d.DK=function(c,d){d.length<a.cipherBlockSize&&(d=b(8*a.cipherBlockSize,d));for(var f=
a.keyGenerationSeedLength/8,h=new Uint8Array(f),g=0,u=d;g<f;)u=a.encrypt(c,e,u)[1],h.set(u.subarray(0,Math.min(u.byteLength,f-g)),g),g+=u.byteLength;return this.randomToKey(h)};d.deriveKey=function(c,b){var d=new Uint8Array(5);(new DataView(d.buffer)).setUint32(0,b);d[4]=153;var e=this.DK(c,d);d[4]=170;var f=this.DK(c,d);d[4]=85;d=this.DK(c,d);return{C:new sjcl.misc.hmac(arrayutils.toSJCL(e),a.unkeyedHash),E:f,I:new sjcl.misc.hmac(arrayutils.toSJCL(d),a.unkeyedHash)}};d.paddingBytes=function(c){c%=
a.messageBlockSize;return 0!=c?a.messageBlockSize-c:0};var g={};g.sumtype=a.sumtype;g.checksumBytes=a.hmacOutputSize;g.getMIC=function(a,b){return c(a.C,b)};g.verifyMIC=function(a,c,b){return arrayutils.equals(b,this.getMIC(a,c))};d.checksum=g;return[d,g]}function e(a,c){function b(a){for(var c=0;c<a.words.length;c++)a.words[c]&=2139062143}function d(a){a.words.reverse();for(var c=0;c<a.words.length;c++){var b=a.words[c],b=z[b&255]<<24|z[b>>>8&255]<<16|z[b>>>16&255]<<8|z[b>>>24&255];a.words[c]=b}}
function e(a){CryptoJS.enc.Hex.stringify(a)in G&&(a.words[1]^=240)}var f=CryptoJS.enc.Utf8.parse(a),l=arrayutils.toCryptoJS(c),f=f.clone();f.concat(l);l=8-f.sigBytes%8;8==l&&(l=0);4<l?f.concat(CryptoJS.lib.WordArray.create([0,0],l)):0<l&&f.concat(CryptoJS.lib.WordArray.create([0],l));for(var l=CryptoJS.lib.WordArray.create([0,0]),q=!1,r=0;r<f.sigBytes;r+=8){var p=CryptoJS.lib.WordArray.create([f.words[r>>2],f.words[(r>>2)+1]]);b(p);q&&d(p);for(var q=!q,n=0;2>n;n++)l.words[n]^=p.words[n]}g(l);e(l);
f=CryptoJS.DES.encrypt(f,l,{iv:l,padding:w});f=CryptoJS.lib.WordArray.create([(f.ciphertext.words[f.ciphertext.words.length-2]&4278124286)>>>1,(f.ciphertext.words[f.ciphertext.words.length-1]&4278124286)>>>1]);g(f);e(f);return arrayutils.fromCryptoJS(f)}function g(a){for(var c=0;c<a.words.length;c++){var b=a.words[c],b=A[b&127]|A[b>>>8&127]<<8|A[b>>>16&127]<<16|A[b>>>24&127]<<24;a.words[c]=b}}function p(a,c,b){if(void 0===b||0==b.length)b=0;else if(1==b.length)b=b[0];else throw new f.InvalidParameters("Bad string-to-key parameter");
if(0==b)return e(a,c);throw new f.InvalidParameters("Bad DES string-to-key type");}function v(a){if(0!=a.checksumBytes%4)throw"Checksum not an integer number of words";var c=a.checksumBytes/4,b={keyGenerationSeedLength:64,randomToKey:function(a){a=arrayutils.toCryptoJS(a);g(a);return arrayutils.fromCryptoJS(a)}};b.stringToKey=p;b.deriveKey=function(a,c){return a};b.decrypt=function(b,d,e){var h=arrayutils.toCryptoJS(b);d=arrayutils.toCryptoJS(d);e=arrayutils.toCryptoJS(e);var g=CryptoJS.lib.CipherParams.create({ciphertext:e}),
g=CryptoJS.DES.decrypt(g,h,{iv:d,padding:w});if(12>g.sigBytes)throw new f.DecryptionError("Bad format");d=CryptoJS.lib.WordArray.create(g.words.slice(2,2+c));for(var h=CryptoJS.lib.WordArray.create(g.words.slice(2+c),g.sigBytes-12),g=g.clone(),r=0;r<c;r++)g.words[2+r]=0;if(!a.verifyMIC(b,arrayutils.fromCryptoJS(g),arrayutils.fromCryptoJS(d)))throw new f.DecryptionError("Checksum mismatch!");d=CryptoJS.lib.WordArray.create([e.words[e.words.length-2],e.words[e.words.length-1]]);return[arrayutils.fromCryptoJS(d),
arrayutils.fromCryptoJS(h)]};b.encrypt=function(b,d,e){var f=arrayutils.toCryptoJS(b);d=arrayutils.toCryptoJS(d);for(var h=sjcl.random.randomWords(2),g=0;g<c;g++)h.push(0);h=CryptoJS.lib.WordArray.create(h);h.concat(arrayutils.toCryptoJS(e));g=8-h.sigBytes%8;8==g&&(g=0);e=g+3;e=(e-e%4)/4;h.concat(CryptoJS.lib.WordArray.create(sjcl.random.randomWords(e),g));b=arrayutils.toCryptoJS(a.getMIC(b,arrayutils.fromCryptoJS(h)));for(g=0;g<c;g++)h.words[2+g]=b.words[g];f=CryptoJS.DES.encrypt(h,f,{iv:d,padding:w});
d=CryptoJS.lib.WordArray.create([f.ciphertext[f.ciphertext.words.length-2],f.ciphertext[f.ciphertext.words.length-1]]);return[arrayutils.fromCryptoJS(d),arrayutils.fromCryptoJS(f.ciphertext)]};b.paddingBytes=function(a){a%=8;return 0!=a?8-a:a};return b}function D(a,c,b,d){function e(a){sjcl.misc.hmac.call(this,a,sjcl.hash.sha1)}void 0==b&&(b=new Uint8Array([0,0,16,0]));if(4!=b.length)throw new f.InvalidParameters("Bad string-to-key parameter");b=(new DataView(b.buffer,b.byteOffset,b.byteLength)).getUint32(0);
0==b&&(b=4294967296);e.prototype=sjcl.misc.hmac.prototype;a=this.randomToKey(arrayutils.fromSJCL(sjcl.misc.pbkdf2(sjcl.codec.utf8String.toBits(a),arrayutils.toSJCL(c),b,this.keyGenerationSeedLength,e)));return d.DK(a,arrayutils.fromByteString("kerberos"))}function y(c,b,d){c=new sjcl.cipher.aes(arrayutils.toSJCL(c));b=arrayutils.toSJCL(b);d=arrayutils.toSJCL(d);if(4>=d.length)return a(d),d=arrayutils.fromSJCL(c.encrypt(d)),[d,d];d=F.encrypt(c,d,b);c=d.length;0!=c%4&&(c+=4-c%4);c=d.slice(c-8,c-4);
return[arrayutils.fromSJCL(c),arrayutils.fromSJCL(d)]}function B(a,c,b){a=new sjcl.cipher.aes(arrayutils.toSJCL(a));var d=arrayutils.toSJCL(c);c=arrayutils.toSJCL(b);if(4>=c.length){if(128!=sjcl.bitArray.bitLength(c))throw new f.DecryptionError("Bad length");try{return[b,arrayutils.fromSJCL(a.decrypt(c))]}catch(e){if(e instanceof sjcl.exception.corrupt)throw new f.DecryptionError(e.message);throw e;}}else return b=F.decrypt(a,c,d),a=c.length,0!=a%4&&(a+=4-a%4),c=c.slice(a-8,a-4),[arrayutils.fromSJCL(c),
arrayutils.fromSJCL(b)]}function E(a){return new Uint8Array(arrayutils.asUint8Array(a))}var f={DecryptionError:function(a){this.message=a}};f.DecryptionError.prototype.toString=function(){return"DecryptionError: "+this.message};f.InvalidParameters=function(a){this.message=a};f.InvalidParameters.prototype.toString=function(){return"InvalidParameters: "+this.message};f.DECRYPT=0;f.ENCRYPT=1;f.enctype={};f.enctype.des_cbc_crc=1;f.enctype.des_cbc_md4=2;f.enctype.des_cbc_md5=3;f.enctype.des3_cbc_md5=5;
f.enctype.des3_cbc_sha1=7;f.enctype.dsaWithSHA1_CmsOID=9;f.enctype.md5WithRSAEncryption_CmsOID=10;f.enctype.sha1WithRSAEncryption_CmsOID=11;f.enctype.rc2CBC_EnvOID=12;f.enctype.rsaEncryption_EnvOID=13;f.enctype.rsaES_OAEP_ENV_OID=14;f.enctype.des_ede3_cbc_Env_OID=15;f.enctype.des3_cbc_sha1_kd=16;f.enctype.aes128_cts_hmac_sha1_96=17;f.enctype.aes256_cts_hmac_sha1_96=18;f.enctype.rc4_hmac=23;f.enctype.rc4_hmac_exp=24;f.enctype.subkey_keymaterial=65;f.sumtype={};f.sumtype.CRC32=1;f.sumtype.rsa_md4=2;
f.sumtype.rsa_md4_des=3;f.sumtype.des_mac=4;f.sumtype.des_mac_k=5;f.sumtype.rsa_md4_des_k=6;f.sumtype.rsa_md5=7;f.sumtype.rsa_md5_des=8;f.sumtype.rsa_md5_des3=9;f.sumtype.sha1=10;f.sumtype.hmac_sha1_des3_kd=12;f.sumtype.hmac_sha1_des3=13;f.sumtype.sha1_2=14;f.sumtype.hmac_sha1_96_aes128=15;f.sumtype.hmac_sha1_96_aes256=16;var w={pad:function(){},unpad:function(){}},F={encrypt:function(b,d,e,f){if(f&&f.length)throw new sjcl.exception.invalid("cbc can't authenticate data");if(128!==sjcl.bitArray.bitLength(e))throw new sjcl.exception.invalid("cbc iv must be 128 bits");
var g,m=sjcl.bitArray;f=[];if(128>=m.bitLength(d))throw new sjcl.exception.invalid("plaintext must be more than 128 bits");for(g=0;g+8<d.length;g+=4)e=b.encrypt(c(e,d.slice(g,g+4))),f.splice(g,0,e[0],e[1],e[2],e[3]);e=b.encrypt(c(e,d.slice(g,g+4)));g=d.slice(g+4,g+8);d=m.bitLength(g);a(g);b=b.encrypt(c(e,g));f.push(b[0],b[1],b[2],b[3]);e=m.clamp(e,d);for(g=0;g<e.length;g++)f.push(e[g]);return f},decrypt:function(b,d,e,f){if(f&&f.length)throw new sjcl.exception.invalid("cbc can't authenticate data");
if(128!==sjcl.bitArray.bitLength(e))throw new sjcl.exception.invalid("cbc iv must be 128 bits");if(128>=sjcl.bitArray.bitLength(d))throw new sjcl.exception.corrupt("cbc-cts ciphertext must be at least two blocks");var g,m=sjcl.bitArray,l;f=[];for(g=0;g+8<d.length;g+=4)l=d.slice(g,g+4),e=c(e,b.decrypt(l)),f.splice(g,0,e[0],e[1],e[2],e[3]),e=l;l=b.decrypt(d.slice(g,g+4));d=d.slice(g+4,g+8);var p=m.bitLength(d);a(d);g=c(d,l);m=m.clamp(g,p);l=m.slice(0);a(l);d=c(d,c(l,g));b=c(e,b.decrypt(d));f.push(b[0],
b[1],b[2],b[3]);for(g=0;g<m.length;g++)f.push(m[g]);return f}};f.nFold=b;f.RsaMd5Checksum={sumtype:f.sumtype.rsa_md5,checksumBytes:16,getMIC:function(a,c){return arrayutils.fromCryptoJS(CryptoJS.MD5(arrayutils.toCryptoJS(c)))},verifyMIC:function(a,c,b){return arrayutils.equals(b,this.getMIC(a,c))}};f.Crc32Checksum={sumtype:f.sumtype.CRC32,checksumBytes:4,getMIC:function(a,c){var b=crc32(arrayutils.toByteString(c),4294967295)^4294967295,d=new Uint8Array(4);(new DataView(d.buffer)).setUint32(0,b,!0);
return d},verifyMIC:function(a,c,b){return arrayutils.equals(b,this.getMIC(a,c))}};var z=[0,64,32,96,16,80,48,112,8,72,40,104,24,88,56,120,4,68,36,100,20,84,52,116,12,76,44,108,28,92,60,124,2,66,34,98,18,82,50,114,10,74,42,106,26,90,58,122,6,70,38,102,22,86,54,118,14,78,46,110,30,94,62,126,1,65,33,97,17,81,49,113,9,73,41,105,25,89,57,121,5,69,37,101,21,85,53,117,13,77,45,109,29,93,61,125,3,67,35,99,19,83,51,115,11,75,43,107,27,91,59,123,7,71,39,103,23,87,55,119,15,79,47,111,31,95,63,127],A=[1,2,4,
7,8,11,13,14,16,19,21,22,25,26,28,31,32,35,37,38,41,42,44,47,49,50,52,55,56,59,61,62,64,67,69,70,73,74,76,79,81,82,84,87,88,91,93,94,97,98,100,103,104,107,109,110,112,115,117,118,121,122,124,127,128,131,133,134,137,138,140,143,145,146,148,151,152,155,157,158,161,162,164,167,168,171,173,174,176,179,181,182,185,186,188,191,193,194,196,199,200,203,205,206,208,211,213,214,217,218,220,223,224,227,229,230,233,234,236,239,241,242,244,247,248,251,253,254],G={"0101010101010101":1,fefefefefefefefe:1,e0e0e0e0f1f1f1f1:1,
"1f1f1f1f0e0e0e0e":1,"011f011f010e010e":1,"1f011f010e010e01":1,"01e001e001f101f1":1,e001e001f101f101:1,"01fe01fe01fe01fe":1,fe01fe01fe01fe01:1,"1fe01fe00ef10ef1":1,e01fe01ff10ef10e:1,"1ffe1ffe0efe0efe":1,fe1ffe1ffe0efe0e:1,e0fee0fef1fef1fe:1,fee0fee0fef1fef1:1};f.RsaMd5DesChecksum={sumtype:f.sumtype.rsa_md5_des,checksumBytes:24,getMIC:function(a,c){a=arrayutils.toCryptoJS(a);for(var b=0;b<a.words.length;b++)a.words[b]^=4042322160;var b=CryptoJS.lib.WordArray.create(sjcl.random.randomWords(2)),d=b.clone();
d.concat(arrayutils.toCryptoJS(c));d=CryptoJS.MD5(d);b.concat(d);d=CryptoJS.lib.WordArray.create([0,0]);return arrayutils.fromCryptoJS(CryptoJS.DES.encrypt(b,a,{iv:d,padding:w}).ciphertext)},verifyMIC:function(a,c,b){a=arrayutils.toCryptoJS(a);b=arrayutils.toCryptoJS(b);for(var d=0;d<a.words.length;d++)a.words[d]^=4042322160;d=CryptoJS.lib.WordArray.create([0,0]);a=CryptoJS.DES.decrypt(CryptoJS.lib.CipherParams.create({ciphertext:b}),a,{iv:d,padding:w});b=CryptoJS.lib.WordArray.create(a.words.slice(0,
2));b.concat(arrayutils.toCryptoJS(c));return CryptoJS.lib.WordArray.create(a.slice(2)).toString()==CryptoJS.MD5(b).toString()}};f.DesCbcMd5Profile=v(f.RsaMd5Checksum);f.DesCbcMd5Profile.enctype=f.enctype.des_cbc_md5;f.DesCbcMd5Profile.initialCipherState=function(a,c){return new Uint8Array(8)};f.DesCbcMd5Profile.checksum=f.RsaMd5DesChecksum;f.DesCbcCrcProfile=v(f.Crc32Checksum);f.DesCbcCrcProfile.enctype=f.enctype.des_cbc_crc;f.DesCbcCrcProfile.initialCipherState=function(a,c){return a};f.DesCbcCrcProfile.checksum=
f.RsaMd5DesChecksum;f.aesCtsEncrypt=y;f.aesCtsDecrypt=B;var x=d({enctype:f.enctype.aes128_cts_hmac_sha1_96,sumtype:f.sumtype.hmac_sha1_96_aes128,stringToKey:D,keyGenerationSeedLength:128,randomToKey:E,unkeyedHash:sjcl.hash.sha1,hmacOutputSize:12,messageBlockSize:1,encrypt:y,decrypt:B,cipherBlockSize:16});f.Aes128CtsHmacShaOne96=x[0];f.ShaOne96Aes128Checksum=x[1];x=d({enctype:f.enctype.aes256_cts_hmac_sha1_96,sumtype:f.sumtype.hmac_sha1_96_aes256,stringToKey:D,keyGenerationSeedLength:256,randomToKey:E,
unkeyedHash:sjcl.hash.sha1,hmacOutputSize:12,messageBlockSize:1,encrypt:y,decrypt:B,cipherBlockSize:16});f.Aes256CtsHmacShaOne96=x[0];f.ShaOne96Aes256Checksum=x[1];f.encProfiles={};f.encProfiles[f.DesCbcMd5Profile.enctype]=f.DesCbcMd5Profile;f.encProfiles[f.DesCbcCrcProfile.enctype]=f.DesCbcCrcProfile;f.encProfiles[f.Aes128CtsHmacShaOne96.enctype]=f.Aes128CtsHmacShaOne96;f.encProfiles[f.Aes256CtsHmacShaOne96.enctype]=f.Aes256CtsHmacShaOne96;f.sumProfiles={};f.sumProfiles[f.RsaMd5Checksum.sumtype]=
f.RsaMd5Checksum;f.sumProfiles[f.Crc32Checksum.sumtype]=f.Crc32Checksum;f.sumProfiles[f.ShaOne96Aes128Checksum.sumtype]=f.ShaOne96Aes128Checksum;f.sumProfiles[f.ShaOne96Aes256Checksum.sumtype]=f.ShaOne96Aes256Checksum;return f}();(function(){function a(a){return a.replace("\\","\\\\").replace("\x00","\\0").replace("\n","\\n").replace("\t","\\t").replace("\b","\\b").replace("/","\\/").replace("@","\\@")}krb.realm="ATHENA.MIT.EDU";krb.supportedEnctypes=[kcrypto.enctype.aes256_cts_hmac_sha1_96,kcrypto.enctype.aes128_cts_hmac_sha1_96,kcrypto.enctype.des_cbc_crc,kcrypto.enctype.des_cbc_md5];krb.Principal=function(a,b){this.principalName=a;this.realm=b};krb.Principal.prototype.nameToString=function(){for(var c=[],b=0;b<this.principalName.nameString.length;b++)c.push(a(this.principalName.nameString[b]));
return c.join("/")};krb.Principal.prototype.toString=function(){return this.nameToString()+"@"+a(this.realm)};krb.Principal.prototype.toStringShort=function(){return this.realm==krb.realm?this.nameToString():this.toString()};krb.Principal.fromString=function(a){for(var b=[],d="",e=!1,g=0;g<a.length;g++)if("\\"==a[g]){g++;if(g>=a.length)throw"Malformed principal";switch(a[g]){case "n":d+="\n";break;case "t":d+="\t";break;case "b":d+="\b";break;case "0":d+="\x00";break;default:d+=a[g]}}else if("/"==
a[g]){if(e)throw"Malformed principal";b.push(d);d=""}else if("@"==a[g]){if(e)throw"Malformed principal";b.push(d);d="";e=!0}else d+=a[g];e||(b.push(d),d=krb.realm);return new krb.Principal({nameType:krb.KRB_NT_PRINCIPAL,nameString:b},d)};krb.Key=function(a,b){this.keytype=a;this.keyvalue=b;this.profile=kcrypto.encProfiles[a];if(void 0===this.profile)throw new Err(Err.Context.KEY,0,"Unsupported enctype "+this.keytype);};krb.Key.makeRandomKey=function(a){var b=kcrypto.encProfiles[a];if(void 0===b)throw new Err(Err.Context.KEY,
0,"Unsupported enctype "+a);var d=sjcl.random.randomWords(b.keyGenerationSeedLength+31>>>5),d=arrayutils.fromSJCL(d).subarray(0,b.keyGenerationSeedLength+7>>>3);return new krb.Key(a,b.randomToKey(d))};krb.Key.prototype.decrypt=function(a,b){if(b.etype!=this.keytype)throw new Err(Err.Context.KEY,1,"Key types do not match");var d=this.profile.deriveKey(this.keyvalue,a);return this.profile.decrypt(d,this.profile.initialCipherState(d,kcrypto.DECRYPT),b.cipher)[1]};krb.Key.prototype.decryptAs=function(a,
b,d){return a.decodeDERPrefix(this.decrypt(b,d))[0]};krb.Key.prototype.encrypt=function(a,b){var d=this.profile.deriveKey(this.keyvalue,a);return{etype:this.keytype,cipher:this.profile.encrypt(d,this.profile.initialCipherState(d,kcrypto.ENCRYPT),b)[1]}};krb.Key.prototype.encryptAs=function(a,b,d){return this.encrypt(b,a.encodeDER(d))};krb.Key.prototype.checksum=function(a,b){var d=this.profile.deriveKey(this.keyvalue,a);return{cksumtype:this.profile.checksum.sumtype,checksum:this.profile.checksum.getMIC(d,
b)}};krb.Key.prototype.toDict=function(){return{keytype:this.keytype,keyvalue:arrayutils.toBase64(this.keyvalue)}};krb.Key.fromDict=function(a){return new krb.Key(a.keytype,arrayutils.fromBase64(a.keyvalue))};krb.Key.fromPassword=function(a,b,d,e){var g=kcrypto.encProfiles[a];if(void 0===g)throw new Err(Err.Context.KEY,2,"Unsupported enctype "+a);return new krb.Key(a,g.stringToKey(b,d,e))};krb.Session=function(a,b){this.client=new krb.Principal(a.cname,a.crealm);this.ticket=a.ticket;this.key=new krb.Key(b.key.keytype,
b.key.keyvalue);this.flags=b.flags;this.authtime=b.authtime;this.starttime=b.starttime;this.endtime=b.endtime;this.renewTill=b.renewTill;this.service=new krb.Principal(b.sname,b.srealm);this.caddr=b.caddr};krb.Session.fromDict=function(a){return new krb.Session({crealm:a.crealm,cname:a.cname,ticket:{tktVno:a.ticket.tktVno,realm:a.ticket.realm,sname:a.ticket.sname,encPart:{kvno:a.ticket.encPart.kvno,etype:a.ticket.encPart.etype,cipher:arrayutils.fromBase64(a.ticket.encPart.cipher)}}},{key:{keytype:a.key.keytype,
keyvalue:arrayutils.fromBase64(a.key.keyvalue)},lastReq:a.lastReq,nonce:a.nonce,keyExpiration:a.keyExpiration,flags:a.flags,authtime:new Date(a.authtime),starttime:null==a.starttime?void 0:new Date(a.starttime),endtime:new Date(a.endtime),renewTill:null==a.renewTill?void 0:new Date(a.renewTill),srealm:a.srealm,sname:a.sname,caddr:a.caddr})};krb.Session.prototype.toDict=function(){return{crealm:this.client.realm,cname:this.client.principalName,ticket:{tktVno:this.ticket.tktVno,realm:this.ticket.realm,
sname:this.ticket.sname,encPart:{kvno:this.ticket.encPart.kvno,etype:this.ticket.encPart.etype,cipher:arrayutils.toBase64(this.ticket.encPart.cipher)}},key:this.key.toDict(),flags:this.flags,authtime:this.authtime.getTime(),starttime:null==this.starttime?void 0:this.starttime.getTime(),endtime:this.endtime.getTime(),renewTill:null==this.renewTill?void 0:this.renewTill.getTime(),srealm:this.service.realm,sname:this.service.principalName,caddr:this.caddr}};krb.Session.prototype.timeRemaining=function(){return this.endtime.getTime()-
(new Date).getTime()};krb.Session.prototype.isExpired=function(){return 0>this.timeRemaining()};krb.Session.prototype.makeAPReq=function(a,b,d){d=d||{};var e={};e.pvno=krb.pvno;e.msgType=krb.KRB_MT_AP_REQ;e.apOptions=d.apOptions||krb.APOptions.make();e.ticket=this.ticket;var g={};g.authenticatorVno=krb.pvno;g.crealm=this.client.realm;g.cname=this.client.principalName;void 0!==b&&(g.cksum=b);g.ctime=new Date;g.cusec=1E3*g.ctime.getUTCMilliseconds();g.ctime.setUTCMilliseconds(0);sjcl.random.addEntropy(arrayutils.toSJCL(this.key.keyvalue),
8*this.key.keyvalue.length,"key");var p;d.useSubkey&&(p=krb.Key.makeRandomKey(this.key.keytype),g.subkey={keytype:p.keytype,keyvalue:p.keyvalue});var v;d.useSeqNumber&&(v=sjcl.random.randomWords(1)[0]&67108863,g.seqNumber=v);e.apOptions[krb.APOptions.mutual_required]&&(d.etypeNegotiation&&this.key.keytype!==krb.supportedEnctypes[0])&&(b=[{adType:krb.AD_ETYPE_NEGOTIATION,adData:krb.EtypeList.encodeDER(krb.supportedEnctypes)}],b={adType:krb.AD_IF_RELEVANT_TYPE,adData:krb.AD_IF_RELEVANT.encodeDER(b)},
g.authorizationData=[b]);e.authenticator=this.key.encryptAs(krb.Authenticator,a,g);return{apReq:e,subkey:p,seqNumber:v,authenticator:g}}})();
//@ sourceMappingURL=webathena.js.map
